### ISSUE TITLE
BUG: Missing dependencies?

### ISSUE THREAD

**Issue by f403** [StreamController/StreamController#117]
**Describe the bug**
Crashes by start / Doesn't start

**To Reproduce**
1. Install missing dependencies (pip was complaining during istallation): `sudo apt install cmake pkgconf build-essential libdbus-glib-1-dev libgirepository1.0-dev libcairo2-dev`
2. Follow [Installation instructions](https://streamcontroller.github.io/docs/latest/installation/#flatpak)
```bash
git clone https://github.com/Core447/StreamController
cd StreamController
python3 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
sudo apt install xdg-desktop-portal xdg-desktop-portal-gtk libportal1 libportal-gtk4-1 # Doesn't seem to be a problem
python3 main.py
```
3. See error
```text
(.venv) user@os-t14:~/soft/StreamController$ python3 main.py
Traceback (most recent call last):
  File "/home/user/soft/StreamController/main.py", line 35, in <module>
    from src.app import App
  File "/home/user/soft/StreamController/src/app.py", line 25, in <module>
    from src.windows.Store.ResponsibleNotesDialog import ResponsibleNotesDialog
  File "/home/user/soft/StreamController/src/windows/Store/ResponsibleNotesDialog.py", line 22, in <module>
    class ResponsibleNotesDialog(Adw.MessageDialog):
  File "/home/user/soft/StreamController/.venv/lib/python3.10/site-packages/gi/module.py", line 130, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Adw' object has no attribute 'MessageDialog'
```

**Additional context**
Ubuntu 22.04.4 LTS (Jammy Jellyfish)

**Comment by Core447** [comment]
Ubuntu 22.04 is shipping a pretty old version of libadwaita (<1.2) that doesn't have newer widgets like EntryRow and MessageDialog. If you want to use the source version, I recommend upgrading to Ubuntu 24.04.

**Comment by f403** [comment]
I think, it will be useful to collect a list of all dependencies. And maybe later to make a list of supported systems

**Comment by Core447** [comment]
Yeah, I just need to find a good way to generate that list automatically

**Comment by Core447** [comment]
> Ubuntu 22.04 is shipping a pretty old version of libadwaita (<1.2) that doesn't have newer widgets like EntryRow and MessageDialog. If you want to use the source version, I recommend upgrading to Ubuntu 24.04.

I'm gonna close this as there's nothing I can do about this
