### ISSUE TITLE
BUG Error importing plugin com_core447_XXXXXXX: No module named 'plugins'

### ISSUE THREAD

**Issue by ThibF** [StreamController/StreamController#128]
**Describe the bug**
When going through the initial setup, it's written "No decks detected" and no pages/plugins created.
However when manually doing changes, it is displayed by the streamdeck (background color reflected by the hardware) and the deck is detected (when quitting the app, we clearly see Closing deck : XXXXX).

**To Reproduce**
1. install
2. start the app with main.py
3. do the initialization wizard

**Expected behavior**
A detected stream deck with working plugins

**Screenshots**

https://github.com/StreamController/StreamController/assets/18592467/a29f2ddf-b4dc-4406-af40-15803301f783

[logs.log](https://github.com/user-attachments/files/15778706/logs.log)

**Additional context**
I was using streamdeck-ui before, without issue.
I also tested python-elgato-streamdeck, without issue.
I'm not using gnome.
I tried flatpak, with basically the same results.

**Comment by Core447** [comment]
Thanks for the detailed report! Did the app create a `plugins` dir in `~/.var/app/com.core447.StreamController/data`?

**Comment by ThibF** [comment]
Yes :
```
$ ls ~/.var/app/com.core447.StreamController/data                                       
Assets  cache  logs  pages  plugins  settings  Store
```

**Comment by Core447** [comment]
Interesting... The weird thing is that I don't get this error with a fresh installation from flathub... I'll dig a little deeper in the next few days.

**Comment by Core447** [comment]
Can you please remove the the try/except block [here](https://github.com/StreamController/StreamController/blob/e83fdfc4caa02da4186379adf4f892810096981d/src/backend/PluginManager/PluginManager.py#L31) so that we can get a more detailed error?

**Comment by ThibF** [comment]
Here it is:
```
Cloning into '/home/thibf/.var/app/com.core447.StreamController/data/plugins/com_gapls_AudioControl'...
remote: Enumerating objects: 314, done.
remote: Counting objects: 100% (314/314), done.
remote: Compressing objects: 100% (177/177), done.
remote: Total 314 (delta 180), reused 259 (delta 129), pack-reused 0
Receiving objects: 100% (314/314), 567.70 KiB | 10.32 MiB/s, done.
Resolving deltas: 100% (180/180), done.
HEAD is now at d4b6f3d Fix(Imports): Imports still not working because python is weird
Exception in thread Thread-5 (_on_start_button_click):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/thibf/repo/StreamController/src/windows/Onboarding/OnboardingWindow.py", line 322, in _on_start_button_click
    asyncio.run(gl.store_backend.install_plugin(plugin))
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/thibf/repo/StreamController/src/backend/Store/StoreBackend.py", line 664, in install_plugin
    gl.plugin_manager.load_plugins()
  File "/home/thibf/repo/StreamController/src/backend/PluginManager/PluginManager.py", line 31, in load_plugins
    importlib.import_module(f"plugins.{folder}.main")
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plugins'
```

**Comment by Core447** [comment]
To me, it looks like [this line](https://github.com/StreamController/StreamController/blob/f1ad2453c9b3d1de5118781bcb94597f056aee9e/globals.py#L32) doesn't work properly. However, I have no idea, why nobody else is experiencing this.

**Comment by Core447** [comment]
Which system/distro are you using?

**Comment by ThibF** [comment]
Looking into this issue, I did this patch:
```
--- a/globals.py
+++ b/globals.py
@@ -28,8 +28,12 @@ if os.getenv("PLUGIN_DIR") is not None:
     if os.path.exists(os.path.join(DATA_PATH, "plugins")):
         log.warning(f"You're using a plugin dir path outside of your data dir, but also have a plugin dir in the data dir. This may cause problems.")
 
+
+log.warning("DATA_PATH: "+ DATA_PATH)
+log.warning("SYS PATH: "+str(sys.path))
 # Add data path to sys.path
 sys.path.append(DATA_PATH)
+log.warning("SYS PATH: "+str(sys.path))
```
And here is the result

```
2024-06-19 21:08:36.721 | WARNING  | globals:<module>:32 - DATA_PATH: /home/thibf/.var/app/com.core447.StreamController/data
2024-06-19 21:08:36.721 | WARNING  | globals:<module>:33 - SYS PATH: ['/home/thibf/repo/StreamController', '/usr/lib/python312.zip', '/usr/lib/python3.12', '/usr/lib/python3.12/lib-dynload', '/home/thibf/repo/StreamController/.venv/lib/python3.12/site-packages']
2024-06-19 21:08:36.721 | WARNING  | globals:<module>:36 - SYS PATH: ['/home/thibf/repo/StreamController', '/usr/lib/python312.zip', '/usr/lib/python3.12', '/usr/lib/python3.12/lib-dynload', '/home/thibf/repo/StreamController/.venv/lib/python3.12/site-packages', '/home/thibf/.var/app/com.core447.StreamController/data']
```

I'm on Ubuntu 24.04

**Comment by Core447** [comment]
> And here is the result
> 
> ```
> 2024-06-19 21:08:36.721 | WARNING  | globals:<module>:32 - DATA_PATH: /home/thibf/.var/app/com.core447.StreamController/data
> 2024-06-19 21:08:36.721 | WARNING  | globals:<module>:33 - SYS PATH: ['/home/thibf/repo/StreamController', '/usr/lib/python312.zip', '/usr/lib/python3.12', '/usr/lib/python3.12/lib-dynload', '/home/thibf/repo/StreamController/.venv/lib/python3.12/site-packages']
> 2024-06-19 21:08:36.721 | WARNING  | globals:<module>:36 - SYS PATH: ['/home/thibf/repo/StreamController', '/usr/lib/python312.zip', '/usr/lib/python3.12', '/usr/lib/python3.12/lib-dynload', '/home/thibf/repo/StreamController/.venv/lib/python3.12/site-packages', '/home/thibf/.var/app/com.core447.StreamController/data']
> ```
> 
> I'm on Ubuntu 24.04

Looks fine



> I'm on Ubuntu 24.04

This issue is very weird, I have no problems on Ubuntu 24.04:
![image](https://github.com/StreamController/StreamController/assets/100139110/84322047-7ea8-4e4c-b9af-4f1b75b3d9d6)

**Comment by ThibF** [comment]
So I tried:
- Hardcoding the import to avoid use importlib => fail
- open an interactive session of python3 that add the correct path and import the plugins =>works
- Display PATH path while loading plugins => Correct path
- Sleeping before the import in case of race condition => Doesn't change anything

I came back to the flatpack and it works (!?).
I don't have any idea where this issue is coming from and not sure where to go forward.

**Comment by Core447** [comment]
The strange thing is that you had the issue on the Flatpak as well, which should be exactly the same for everyone and as far as I know it works for everyone else...

> open an interactive session of python3 that add the correct path and import the plugins =>works

This is so weird... This should be exactly the same as the app is doing

**Comment by Core447** [comment]
I now had the same problem during the onboarding for a fresh install. The problem was that the plugins directory was not present in the data dir when it (data dir) was added to the paths. However, restarting the app fixed it. 20e8e9750d2f815f6567bbd1d6274dca0a1b6282 Should fix it for the first start.

However, if I understand correctly, you not only had the problem at the initial start, but also after restarts, right?

**Comment by ThibF** [comment]
I honestly didn't try, but that seems to be the issue, I'm going to backup my data directory and try it again.

**Comment by ThibF** [comment]
Pulled the latest version, it works ! That was issue, nice finding. Thanks for your work !

**Comment by Core447** [comment]
Hm, nice that it works, but I just found [these](https://github.com/StreamController/StreamController/blob/c4dfdab4519eac46eed3e31f2817fda8a05ed479/src/backend/PluginManager/PluginManager.py#L23-L24) lines should do basically the same... And I'm not sure why I never got that message before... Something to keep an eye on
