### ISSUE TITLE
Unabled to start app

### ISSUE THREAD

**Issue by general03** [StreamController/StreamController#154]
**Describe the bug**
I got error when I execute cmd `python main.py`

**To Reproduce**
1. Follow the installation page 
2. Execute command  `python main.py`

**Expected behavior**
Display app UI without error

**Screenshots**
```
Traceback (most recent call last):
  File "/home/drigaudie/projects/StreamController/main.py", line 44, in <module>
    from src.app import App
  File "/home/drigaudie/projects/StreamController/src/app.py", line 25, in <module>
    from src.windows.Store.ResponsibleNotesDialog import ResponsibleNotesDialog
  File "/home/drigaudie/projects/StreamController/src/windows/Store/ResponsibleNotesDialog.py", line 22, in <module>
    class ResponsibleNotesDialog(Adw.MessageDialog):
  File "/home/drigaudie/projects/StreamController/.venv/lib/python3.10/site-packages/gi/module.py", line 130, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Adw' object has no attribute 'MessageDialog'
```

**Additional context**
Ubuntu 22.04.4 LTS

**Comment by Core447** [comment]
Unfortunately Ubuntu 22.04 comes with a pretty old version of libadwaita. I recommend updating to 24.04 if you want to run the  source version.

**Comment by general03** [comment]
Arg, I can't upgrade my computer. Which version is required for `libadwaita` ?

**Comment by Core447** [comment]
For a long time it required 1.4, but now it should be 1.5. If you still want to use the app you can just install it as a Flatpak from Flathub
