### ISSUE TITLE
Deck Settings Brightness overrides Page Overwrite default deck brightness

### ISSUE THREAD

**Issue by KaJe5380** [StreamController/StreamController#180]
**Describe the bug**
`Page Settings` > `Overwrite default deck brightness` should be the brightness set.
Somehow, the StreamController regular brightness setting overrides this.

[![Deck Brightness bug](http://img.youtube.com/vi/f6X5s64sUD4/0.jpg)](http://www.youtube.com/watch?v=f6X5s64sUD4 "Deck Brightness bug")

**To Reproduce**
1. Set regular Deck Brightness within Settings to 4.
2. Go to page settings and enable `Overwrite default deck brightness`
3. Set `Overwrite default deck brightness` to 80
4. Change pages away from this override
5. Swap page to the page with the `Overwrite`

**Expected behavior**
Deck should be set to brightness 80, not 4. You get to watch as the Deck brightness flicks between high then low.

**Screenshots**
![image](https://github.com/user-attachments/assets/61721aa1-856e-44c2-81fe-4c7b0ed5879d)
![image](https://github.com/user-attachments/assets/a91139d1-fb65-4c86-b756-b9ef3f34d572)

**Additional context**
Tested on a StreamDeck+

This is my Linux outputted via FastFetch within Konsole:
![image](https://github.com/user-attachments/assets/1481344d-2088-46c9-925c-c2b05d2540c7)

**Comment by Core447** [comment]
Fixed with ed9c34cf22f398b65814f0dcd7184df936e9fd8e, we can keep this opened until it's available on the Flatpak

Update: Seems still broken in some cases

**Comment by KaJe5380** [comment]
```
2024-07-20 03:59:17.194 | ERROR    | src.windows.mainWindow.elements.PageSettings.DeckGroup:on_toggle_overwrite:137 - An error has been caught in function 'on_toggle_overwrite', process 'MainProcess' (3), thread 'MainThread' (131776685471552):
Traceback (most recent call last):

  File "/app/bin/StreamController/main.py", line 276, in <module>
    main()
    └ <function main at 0x77d95fd4e020>

  File "/app/bin/StreamController/main.py", line 273, in main
    load()
    └ <function load at 0x77d95fd4cf40>

  File "/app/bin/StreamController/main.py", line 99, in load
    gl.main = Main(application_id="com.core447.StreamController", deck_manager=gl.deck_manager)
    │         │                                                                │  └ <src.backend.DeckManagement.DeckManager.DeckManager object at 0x77d9465abf50>
    │         │                                                                └ <module 'globals' from '/app/bin/StreamController/globals.py'>
    │         └ <class '__main__.Main'>
    └ <module 'globals' from '/app/bin/StreamController/globals.py'>

  File "/app/bin/StreamController/main.py", line 90, in __init__
    self.app.run(gl.argparser.parse_args().app_args)
    │    │   │   │  │         └ <function ArgumentParser.parse_args at 0x77d9a508b380>
    │    │   │   │  └ ArgumentParser(prog='main.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handl...
    │    │   │   └ <module 'globals' from '/app/bin/StreamController/globals.py'>
    │    │   └ <function Application.run at 0x77d9a3d3c040>
    │    └ <app.App object at 0x77d952b61580 (src+app+App at 0x59067bd4d420)>
    └ <__main__.Main object at 0x77d94792de10>

  File "/usr/lib/python3.11/site-packages/gi/overrides/Gio.py", line 42, in run
    return Gio.Application.run(self, *args, **kwargs)
           │   │           │   │      │       └ {}
           │   │           │   │      └ ([],)
           │   │           │   └ <app.App object at 0x77d952b61580 (src+app+App at 0x59067bd4d420)>
           │   │           └ gi.FunctionInfo(run, bound=None)
           │   └ <class 'gi.repository.Gio.Application'>
           └ <IntrospectionModule 'Gio' from '/usr/lib/x86_64-linux-gnu/girepository-1.0/Gio-2.0.typelib'>

  File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 629, in update_ui_on_page_change
    settings_group.brightness.load_defaults_from_page()
    │              │          └ <function Brightness.load_defaults_from_page at 0x77d97a196840>
    │              └ <DeckGroup.Brightness object at 0x77d946174040 (src+windows+mainWindow+elements+PageSettings+DeckGroup+Brightness at 0x59067b...
    └ <DeckGroup.DeckGroup object at 0x77d946174d80 (src+windows+mainWindow+elements+PageSettings+DeckGroup+DeckGroup at 0x59067be3...

  File "/app/bin/StreamController/src/windows/mainWindow/elements/PageSettings/DeckGroup.py", line 152, in load_defaults_from_page
    self.overwrite_switch.set_active(active)
    │    │                │          └ True
    │    │                └ gi.FunctionInfo(set_active, bound=None)
    │    └ <Gtk.Switch object at 0x77d9461720c0 (GtkSwitch at 0x59067bf4fd10)>
    └ <DeckGroup.Brightness object at 0x77d946174040 (src+windows+mainWindow+elements+PageSettings+DeckGroup+Brightness at 0x59067b...

> File "/app/bin/StreamController/src/windows/mainWindow/elements/PageSettings/DeckGroup.py", line 137, in on_toggle_overwrite
    deck_controller.load_page(deck_controller.active_page, load_screensaver=False, load_background=False, load_keys=False)
    │               │         │               └ <src.backend.PageManagement.Page.Page object at 0x77d94617c310>
    │               │         └ <src.backend.DeckManagement.DeckController.DeckController object at 0x77d946107550>
    │               └ <function DeckController.load_page at 0x77d96cfbe700>
    └ <src.backend.DeckManagement.DeckController.DeckController object at 0x77d946107550>

TypeError: DeckController.load_page() got an unexpected keyword argument 'load_keys'

```

It happens randomly when swapping between two pages.
~One with overwrite brightness of 80 and the other being 4.~
Seems to be when swapping from a page that has overwrite and another that doesn't have an overwrite.

**Comment by Core447** [comment]
> It happens randomly when swapping between two pages.
> ~One with overwrite brightness of 80 and the other being 4.~
> Seems to be when swapping from a page that has overwrite and another that doesn't have an overwrite.

Fixed with 54dde86eeb688b83615b4e3d0fde5747c9951355

**Comment by zeridon** [comment]
Seems that this is happening if you ever tried to set custom brightness per page (you are switching to).

e.g. with:

```
    "brightness": {
        "overwrite": false,
        "value": 30
    },
```

in a page i see the brightness flash. Without it i do not.

**Comment by ImDevinC** [comment]
I can no longer reproduce this issue. Closing as it should be resolved and we've received no feedback otherwise. Feel free to comment if you can still reproduce
