### ISSUE TITLE
Crash when changing page

### ISSUE THREAD

**Issue by jeremy-flusin** [StreamController/StreamController#200]
**Describe the bug**

Hi there,
For the past few days, my stream deck has been crashing unexpectedly whenever I try to switch pages. All the other buttons work fine, but every time I press a button to change pages, the stream deck crashes and becomes unresponsive until I unplug and replug it. After doing that, the page changes work normally again until I restart my computer.

**To Reproduce**
* Boot Ubuntu, log in
* Wait until Stream deck seems initialized
* Try to change page with a dedicated button
* Page does not change, and all the other buttons become unresponsive

**Expected behavior**
* Active page should change

**Additional context**
* Ubuntu 24.04 LTS
* Stream Deck MK.2 (15 buttons)
* StreamController 1.5.0-beta.6 from Flathub

**Please note**
* I'm also running a dual boot with Windows 11 and official stream deck software, if that matters.
* Everything worked fine for several weeks, and this problem just appeared out of nowhere. I'm not even sure that I updated anything on my system.

**Logs when crashing**

```
2024-08-13 14:43:41.121 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Run Command with id com_core447_OSPlugin::RunCommand
2024-08-13 14:43:41.121 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Run Command with id com_core447_OSPlugin::RunCommand
2024-08-13 14:43:41.122 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Run Command with id com_core447_OSPlugin::RunCommand
2024-08-13 14:43:41.122 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Run Command with id com_core447_OSPlugin::RunCommand
2024-08-13 14:43:41.122 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Changer La Page with id com_core447_DeckPlugin::ChangePage
2024-08-13 14:43:41.122 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Changer La Page with id com_core447_DeckPlugin::ChangePage
2024-08-13 14:43:41.122 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Changer La Page with id com_core447_DeckPlugin::ChangePage
2024-08-13 14:43:41.123 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action CPU Graph with id com_core447_OSPlugin::CPU_Graph
2024-08-13 14:43:41.134 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Memory Graph with id com_core447_OSPlugin::RAM_Graph
2024-08-13 14:43:41.140 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Hotkey with id com_core447_OSPlugin::Hotkey
2024-08-13 14:43:41.140 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Hotkey with id com_core447_OSPlugin::Hotkey
2024-08-13 14:43:41.141 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Run Command with id com_core447_OSPlugin::RunCommand
2024-08-13 14:43:41.144 | DEBUG    | src.backend.PageManagement.Page:load:77 - Loaded page Seconde page in 0.02 seconds
2024-08-13 14:43:41.148 | INFO     | src.backend.DeckManagement.DeckController:load_page:670 - Loading page Seconde page on deck A00SA4122JZEML
2024-08-13 14:43:41.223 | INFO     | src.backend.DeckManagement.DeckController:load_background:522 - Loading background in thread: 124359727384256
2024-08-13 14:43:41.272 | INFO     | src.backend.DeckManagement.DeckController:load_page:699 - Loaded page Seconde page on deck A00SA4122JZEML
2024-08-13 14:43:41.307 | ERROR    | src.backend.DeckManagement.DeckController:run:86 - An error has been caught in function 'run', process 'MainProcess' (3), thread 'MediaPlayerThread' (124359727384256):
Traceback (most recent call last):

  File "/usr/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x711b1e3034c0>
    └ <MediaPlayerThread(MediaPlayerThread, started daemon 124359727384256)>
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function MediaPlayerThread.run at 0x711af158d080>
    └ <MediaPlayerThread(MediaPlayerThread, started daemon 124359727384256)>

  File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 210, in run
    self.perform_media_player_tasks()
    │    └ <function MediaPlayerThread.perform_media_player_tasks at 0x711af158d6c0>
    └ <MediaPlayerThread(MediaPlayerThread, started daemon 124359727384256)>

  File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 295, in perform_media_player_tasks
    task.run()
    │    └ <function MediaPlayerTask.run at 0x711af93ffd80>
    └ MediaPlayerTask(deck_controller=<src.backend.DeckManagement.DeckController.DeckController object at 0x711ad5555d50>, page=<sr...

> File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 86, in run
    self._callable(*self.args, **self.kwargs)
    │    │          │    │       │    └ {'update': False}
    │    │          │    │       └ MediaPlayerTask(deck_controller=<src.backend.DeckManagement.DeckController.DeckController object at 0x711ad5555d50>, page=<sr...
    │    │          │    └ (<src.backend.PageManagement.Page.Page object at 0x711ad7155610>,)
    │    │          └ MediaPlayerTask(deck_controller=<src.backend.DeckManagement.DeckController.DeckController object at 0x711ad5555d50>, page=<sr...
    │    └ <bound method DeckController.load_all_inputs of <src.backend.DeckManagement.DeckController.DeckController object at 0x711ad55...
    └ MediaPlayerTask(deck_controller=<src.backend.DeckManagement.DeckController.DeckController object at 0x711ad5555d50>, page=<sr...

  File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 605, in load_all_inputs
    futures.append(executor.submit(self.load_input, controller_input, page, update))
    │       │      │        │      │    │           │                 │     └ False
    │       │      │        │      │    │           │                 └ <src.backend.PageManagement.Page.Page object at 0x711ad7155610>
    │       │      │        │      │    │           └ <src.backend.DeckManagement.DeckController.ControllerKey object at 0x711ad5563010>
    │       │      │        │      │    └ <function DeckController.load_input at 0x711af158f6a0>
    │       │      │        │      └ <src.backend.DeckManagement.DeckController.DeckController object at 0x711ad5555d50>
    │       │      │        └ <function ThreadPoolExecutor.submit at 0x711b045bb100>
    │       │      └ <concurrent.futures.thread.ThreadPoolExecutor object at 0x711ad710f8d0>
    │       └ <method 'append' of 'list' objects>
    └ []

  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '

RuntimeError: cannot schedule new futures after interpreter shutdown
2024-08-13 14:43:41.344 | DEBUG    | src.backend.DeckManagement.DeckController:update_all_inputs:432 - Updating all inputs took 0.029558420181274414 seconds
2024-08-13 14:43:44.843 | INFO     | __main__:update_assets:163 - Updating 0 store assets took 22.864734888076782 seconds
2024-08-13 14:43:44.843 | INFO     | __main__:update_assets:163 - Updating 0 store assets took 22.851038217544556 seconds
```

Let me know if you need anything else from me. Thank you for reading.

**Comment by Core447** [comment]
Is this the content of the log file or the output of the command line? If it's from the file, could you please start the app from the command line and share the output?

Sorry for the inconvenience! I hope we can fix this soon

**Comment by jeremy-flusin** [comment]
This is indeed the content of the log file.

I wanted to launch the app from the command line, but the output said that an instance was already running. Not surprising, since it launches at startup. After removing the app from the startup applications, rebooting, and launching the app via CLI, I can not reproduce the problem. It seems to only happen with the instance launched at startup.

EDIT: 
Okay, I've got some news. I noticed something weird while removing the app from the startup applications. It seems that the StreamController item was duplicated in the listing of the startup apps for some reason:

![image](https://github.com/user-attachments/assets/f7830c6e-e1b7-4eb2-8d76-dbfe47d90929)

After removing one of the two lines, it seems to work as expected, and I can switch pages as soon as the app started. I'm still trying to reboot again and again to see if I reproduce the problem and I'll let you know.

EDIT 2: 
After several reboots with only one entry in the startup apps, everything works as expected. Just to be sure, I manually added a second entry like it was before, and I reproduced the bug immediately.

So, as a workaround, removing the duplicate entry seems to solve the problem. But I still have no idea on how this dupe appeared in the first place.

I hope this helps!

**Comment by Core447** [comment]
Ok, thanks for the testing! Having two instances running can indeed result in some very weird issues. 

The problem with the duplicated entries has also happened for some other people, but I have no idea what's causing this.

An easier way to close the running instance than removing it from the autostart and restarting, is to use the quit option in the hamburger menu in the header bar of the main window.
