### ISSUE TITLE
Memory leak while screen is locked

### ISSUE THREAD

**Issue by jfbauer432** [StreamController/StreamController#203]
I found what looks to be a very large (~1.4MB/minute) memory leak.  I discovered this after fixing #198.  It only happens while the screen is locked, Lock-decks-when-screen-is-locked is enabled, and you are running on a system that supports locking the deck.

In src/windows/mainWindow/DeckPlus/ScreenBar.py:ScreenBarImage:set_image() 

`self.on_map_tasks.append(lambda: self.set_image(image))`

is called several times a second while the screen is locked.  It looks like that list should be emptied by on_map(), but I never see that being called.

I added some temp code using python tracemalloc and took snapshots when activating and deactivating the lock screen.  Some line numbers below will be off as I also added some temp log messages.  Here is the output.

```
[ Memory usage increase from locking screen to unlocking ]
StreamController/src/windows/mainWindow/DeckPlus/ScreenBar.py:260: size=226 KiB (+225 KiB), count=2065 (+2050), average=112 B
StreamController/.venv/lib/python3.12/site-packages/PIL/Image.py:528: size=156 KiB (+152 KiB), count=2100 (+2044), average=76 B
StreamController/.venv/lib/python3.12/site-packages/PIL/Image.py:531: size=89.7 KiB (+87.9 KiB), count=2082 (+2046), average=44 B
StreamController/src/backend/DeckManagement/DeckController.py:2118: size=80.5 KiB (+80.1 KiB), count=2060 (+2050), average=40 B
StreamController/src/backend/DeckManagement/HelperMethods.py:79: size=89.2 KiB (+65.8 KiB), count=1818 (+1327), average=50 B
StreamController/.venv/lib/python3.12/site-packages/PIL/Image.py:539: size=65.6 KiB (+63.9 KiB), count=1050 (+1022), average=64 B
StreamController/.venv/lib/python3.12/site-packages/PIL/Image.py:530: size=46.1 KiB (+44.9 KiB), count=1050 (+1022), average=45 B
StreamController/.venv/lib/python3.12/site-packages/PIL/ImageFile.py:560: size=37.7 KiB (-44.9 KiB), count=2 (-10), average=18.8 KiB
StreamController/.venv/lib/python3.12/site-packages/PIL/Image.py:2974: size=32.7 KiB (+32.0 KiB), count=1046 (+1025), average=32 B
StreamController/src/backend/DeckManagement/ImageHelpers.py:140: size=26.2 KiB (+22.0 KiB), count=539 (+452), average=50 B

[ Detailed traceback for the top memory hogs ]
  File "StreamController/src/windows/mainWindow/DeckPlus/ScreenBar.py", line 260
    self.on_map_tasks.append(lambda: self.set_image(image))

```

This is using StreamController at commit d286e82 + the 3 commits I added for issue #198.

**Comment by jfbauer432** [comment]
More info.  I had a fake deck in addition to a real one for my Stream Deck Mini.  Removing the fake deck stopped the memory leak.

**Comment by G4PLS** [comment]
Do you have a SD+? This seems like its an issue with the SD+ but can't test because I dont own one

**Comment by jfbauer432** [comment]
I only have a Mini.

**Comment by Core447** [comment]
Thanks for reporting! Do you have a video set as your wallpaper (in the screensaver)?

**Comment by jfbauer432** [comment]
No video, no image.  Just a blank display.  The display backlight stays on though.

**Comment by Core447** [comment]
Can't test it properly right now, but 57431f9aafff564697b69d49e46514651c626579 might/should fix this

**Comment by jfbauer432** [comment]
I gave it a quick try (at 50b1ca6a -- 1 commit later) and the change fixed the memory leak.

**Comment by Core447** [comment]
Nice! Just out of interest: Did you use any special library for the debugging?

**Comment by jfbauer432** [comment]
Python's [tracemalloc](https://docs.python.org/3/library/tracemalloc.html) was used to track down the cause.

**Comment by Core447** [comment]
> Python's [tracemalloc](https://docs.python.org/3/library/tracemalloc.html) was used to track down the cause.

Ok, thank you!

**Comment by martin-schwenke** [comment]
I think I'm seeing this with the latest version (1.5.0-beta.8).  I restarted StreamController (installed from flatpak), killing `flatpak-session-helper` in between stop/start.  At `16:08:15`, `top` said `flatpak-session-helper` was using `312052 KB` of virtual memory.  Without using StreamController, I came back at `17:29:48` and is was using `440288 KB`.  That's an increase of ~128MB in ~80 minutes, so ~1.6MB per minute.

I initially reported #340 but I think the memory leak is related to the CPU usage.  Here are some data points:

```
VM used       |   CPU
(MB)          | (% of a thread)

 310          |   2.3
 312          |   2.6
 440          |   8.3
 475          |   9.2 
 562          |  10.6
 565          |  12.2
 667          |  13.5
 768          |  14.5
1208          |  20.6
1480          |  22.8
6500          |  37.7
```
When I plot that, it doesn't look quite linear, but it is close.

Without looking at the code, I think that what is really happening is something like a list is being appended to and then it is being linearly searched.  As the list grows, the search gets slower and StreamController uses more CPU.

BTW, I've disabled the lock screen setting and nothing changes.

I'm happy to try and debug the code, but I would have to be able to make it work via `pipenv`.  At the moment when I try this, I see:
```
$ python3 main.py 
Traceback (most recent call last):
  File "/home/martins/downloads/StreamController/main.py", line 39, in <module>
    from src.app import App
  File "/home/martins/downloads/StreamController/src/app.py", line 24, in <module>
    from src.windows.Store.ResponsibleNotesDialog import ResponsibleNotesDialog
  File "/home/martins/downloads/StreamController/src/windows/Store/ResponsibleNotesDialog.py", line 16, in <module>
    gi.require_version("Gtk", "4.0")
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/martins/downloads/StreamController/.venv/lib/python3.13/site-packages/gi/__init__.py", line 125, in require_version
    raise ValueError('Namespace %s not available for version %s' %
                     (namespace, version))
ValueError: Namespace Gtk not available for version 4.0
```
This is on Debian testing, and I have `libgtk-4-1` installed.  Am I too far ahead?   I'm clearly missing something...

**Comment by Core447** [comment]
> This is on Debian testing, and I have `libgtk-4-1` installed. Am I too far ahead? I'm clearly missing something...

I will take a look at this when I'm back home next week. Can you please try if installing these packages fixes the error: `gir1.2-xdpgtk4-1.0 libgirepository1.0-dev libportal-gtk4-1 libportal-gtk4-dev`?

**Comment by martin-schwenke** [comment]
> I will take a look at this when I'm back home next week. Can you please try if installing these packages fixes the error: `gir1.2-xdpgtk4-1.0 libgirepository1.0-dev libportal-gtk4-1 libportal-gtk4-dev`?

Thanks.  I thought that I had done that.  The habitual janitor in me must have removed them again after it first failed.  😦 

After that I got a failure that I had originally seen:
```
$ python3 main.py 
Traceback (most recent call last):
  File "/home/martins/downloads/StreamController/main.py", line 39, in <module>
    from src.app import App
  File "/home/martins/downloads/StreamController/src/app.py", line 24, in <module>
    from src.windows.Store.ResponsibleNotesDialog import ResponsibleNotesDialog
  File "/home/martins/downloads/StreamController/src/windows/Store/ResponsibleNotesDialog.py", line 17, in <module>
    gi.require_version("Adw", "1")
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/martins/downloads/StreamController/.venv/lib/python3.13/site-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Adw not available
```
However, installing `libadwaita-1-dev` makes that go away and then it runs.  So, possibly worth adding that package to list of requirements for Ubuntu/Debian.

... but, although my configuration is clearly loaded, with the Stream Deck showing the correct buttons, pressing buttons doesn't do anything.  😦 

The only relevant error during startup is:
```
2025-03-06 13:41:23.062 | INFO     | src.backend.PluginManager.PluginBase:launch_backend:634 - Launching backend: . /home/martins/.var/app/com.core447.StreamController/data/plugins/com_core447_OBSPlugin/backend/.venv/bin/activate && python3 /home/martins/.var/app/com.core447.StreamController/data/plugins/com_core447_OBSPlugin/backend/backend.py --port=41149
python3: error while loading shared libraries: libpython3.12.so.1.0: cannot open shared object file: No such file or directory
backend launched
```
I have tried removing `.venv/` and trying again.  Same result.  It makes sense because I don't have Python 3.12:
```
$ python --version
Python 3.13.2
```
I noticed that 3.12 was referenced here:
```
$ ls -l /home/martins/.var/app/com.core447.StreamController/data/plugins/com_core447_OBSPlugin/backend/.venv/bin/
total 104
-rw-r--r-- 1 martins martins  8786 Mar  3 18:41 Activate.ps1
-rw-r--r-- 1 martins martins  2272 Mar  3 18:41 activate
-rw-r--r-- 1 martins martins   998 Mar  3 18:41 activate.csh
-rw-r--r-- 1 martins martins  2273 Mar  3 18:41 activate.fish
-rwxr-xr-x 1 martins martins   317 Mar  3 18:41 pip
-rwxr-xr-x 1 martins martins   317 Mar  3 18:41 pip3
-rwxr-xr-x 1 martins martins   317 Mar  3 18:41 pip3.12
-rwxr-xr-x 1 martins martins 15672 Mar  3 18:41 python
-rwxr-xr-x 1 martins martins 15672 Mar  3 18:41 python3
-rwxr-xr-x 1 martins martins 15672 Mar  3 18:41 python3.12
-rwxr-xr-x 1 martins martins   316 Mar  3 18:41 rpyc_classic
-rwxr-xr-x 1 martins martins   316 Mar  3 18:41 rpyc_classic.py
-rwxr-xr-x 1 martins martins   317 Mar  3 18:41 rpyc_registry
-rwxr-xr-x 1 martins martins   317 Mar  3 18:41 rpyc_registry.py
-rwxr-xr-x 1 martins martins   312 Mar  3 18:41 wsdump
```
After some random hackery in `/home/martins/.var/app/com.core447.StreamController/` it appears to be working.  Not sure what I did.  Removed the whole thing and realised that nuked my config, so tried restoring parts from backup, before just restoring the whole thing.  Now that directory refers to 3.13 and everything works...

... except the  systray icon is blank!  Worse things could happen...  😉 

Now, back to the original issue: I'll wait to see if any processes grow or if CPU usage of a relevant process starts going wild.

**Comment by ImDevinC** [comment]
@martin-schwenke is this still an issue?

**Comment by martin-schwenke** [comment]
> [@martin-schwenke](https://github.com/martin-schwenke) is this still an issue?

Testing.  Will send another response in about a day.

I've been running from source via `pip` and a `venv`.   The leak was in `flatpak-session-helper`, so trying the Flatpak install for the first time since March.

**Comment by martin-schwenke** [comment]
The bug is still there.

However, I've now found https://github.com/flatpak/flatpak/issues/5821, applied the fix and `flatpak-session-helper` no longer leaks.

However, I think I might have hijacked this issues because my brain matched "memory leak".  It looks like the original memory leak was in StreamController and was fixed, but the issue was never closed.  The leak I was seeing was in `flatpak-session-helper`.  I had assumed an app-specific bug, partly because Flatpak is so widely used that I couldn't believe it would have a bug this serious.  Sorry if I hijacked an irrelevant issue...

**Comment by ImDevinC** [comment]
No worries. Going to close this based on the feedback, thanks for following up!
