### ISSUE TITLE
Can't open using the GitHub method

### ISSUE THREAD

**Issue by CharlesCanlom** [StreamController/StreamController#251]
**Describe the bug**
I tried installing the app using the GitHub method, but every time i use `python3 main.py` to open it, it always put this callback thingy.

**To Reproduce**
1. Follow the instructions using the GitHub method
2. switch the branch to sd-neo
3. run `python3 main.py`
4. Saw a callback.

**Expected behavior**
I expected it to show the app on first try. 

**Screenshots**

**Additional context**
I'm running Zorin Os 17.2, and here's the error message:
```shell
Traceback (most recent call last):
  File "/home/olivereverest/StreamController/main.py", line 40, in <module>
    from src.app import App
  File "/home/olivereverest/StreamController/src/app.py", line 35, in <module>
    from src.windows.mainWindow.mainWindow import MainWindow
  File "/home/olivereverest/StreamController/src/windows/mainWindow/mainWindow.py", line 32, in <module>
    from src.windows.mainWindow.elements.Sidebar.Sidebar import Sidebar
  File "/home/olivereverest/StreamController/src/windows/mainWindow/elements/Sidebar/Sidebar.py", line 21, in <module>
    from src.windows.mainWindow.elements.PageSelector import PageSelector
  File "/home/olivereverest/StreamController/src/windows/mainWindow/elements/PageSelector.py", line 30, in <module>
    from src.windows.PageManager.PageManager import PageManager
  File "/home/olivereverest/StreamController/src/windows/PageManager/PageManager.py", line 25, in <module>
    from src.windows.PageManager.elements.PageSelector import PageSelector
  File "/home/olivereverest/StreamController/src/windows/PageManager/elements/PageSelector.py", line 40, in <module>
    class PageSelector(Adw.NavigationPage):
  File "/home/olivereverest/StreamController/.venv/lib/python3.10/site-packages/gi/module.py", line 130, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Adw' object has no attribute 'NavigationPage'

```

**Comment by Core447** [comment]
Unfortunately, your Adw version seems to be too old. You need at least version 1.4.

**Comment by pblanton** [comment]
I have the same issue and I have checked that libadwaita is current...

`libadwaita-1-0 is already the newest version (1.3.3-0ubuntu0.23.04.1+zorin2).`

Still have the same issue.

**Comment by Core447** [comment]
> is current...
> 
> ``

Yeah, it's the newest that your distro gets, but no the newest available. You can just use the Flatpak to avoid this issue.

**Comment by CharlesCanlom** [comment]
> You can just use the Flatpak to avoid this issue.

But I wanted to use the sd-neo branch because I have a Stream Deck Neo.

**Comment by Core447** [comment]
> But I wanted to use the sd-neo branch because I have a Stream Deck Neo.

Unfortunately it seems like your distro doesn't ship any newer version of adwaita. You can either wait until the next release (which will come with sd-neo support) or you manually create the Flatpak. To do the later please run the commands from the first image until you reach the read line. Then edit the `com.core447.....` file and change the branch from `main` to `sd-neo` where the arrow is. Then continue with the commands from the first image. You may need to install `flatpak-builder` before running the very last command.
![cmd](https://github.com/user-attachments/assets/eaebc75d-17f4-4abb-8c6a-ea904cdedbac)
![cmd2](https://github.com/user-attachments/assets/f9374e56-c2fa-403e-b857-0f6ff8ff1fc0)

**Comment by Core447** [comment]
> But I wanted to use the sd-neo branch because I have a Stream Deck Neo.

The sd neo is now supported by the Flatpak version.
