### ISSUE TITLE
AttributeError: 'gi.repository.Adw' object has no attribute 'NavigationPage'

### ISSUE THREAD

**Issue by pblanton** [StreamController/StreamController#253]
**Describe the bug**
Using ZorinOS (Zorin OS 17.2 Core) and following the installation instructions from https://streamcontroller.github.io/docs/latest/installation/, I get the following error...

**To Reproduce**
1. Be using ZorinOS 17.2 Core (Ubuntu 24.04 descendant)
2. Follow the instructions here : 
3. Get following error when attempting to run main.py (Step 8 in aforementioned installation instructions)...

(.venv) pblanton@ThreadRipper:~/Downloads/StreamController$ python3 main.py
Traceback (most recent call last):
  File "/home/pblanton/Downloads/StreamController/main.py", line 16, in <module>
    import setproctitle
ModuleNotFoundError: No module named 'setproctitle'

**Expected behavior**
Streamdeck should run

**Screenshots**
![image](https://github.com/user-attachments/assets/191719ec-4328-4e23-b6e8-bb2160ab9802)

**Additional context**
I'm about to spin up PyCharm and see if I can further debug the issue.

**Comment by pblanton** [comment]
Error is with the dbus-python package.

This command: `pip install dbus-python`

results in ...

```
Collecting dbus-python==1.3.2
  Using cached dbus-python-1.3.2.tar.gz (605 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [94 lines of output]
      + meson setup /tmp/pip-install-4umkat69/dbus-python_e340cafd355445b5b3b3e8f6933865ea /tmp/pip-install-4umkat69/dbus-python_e340cafd355445b5b3b3e8f6933865ea/.mesonpy-w5lbswi8 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-4umkat69/dbus-python_e340cafd355445b5b3b3e8f6933865ea/.mesonpy-w5lbswi8/meson-python-native-file.ini
      The Meson build system
      Version: 1.5.2
      Source dir: /tmp/pip-install-4umkat69/dbus-python_e340cafd355445b5b3b3e8f6933865ea
      Build dir: /tmp/pip-install-4umkat69/dbus-python_e340cafd355445b5b3b3e8f6933865ea/.mesonpy-w5lbswi8
      Build type: native build
      Project name: dbus-python
```

<... snip ...>

```
      dbus-gmain| Found pkg-config: YES (/usr/bin/pkg-config) 0.29.2
      dbus-gmain| Did not find CMake 'cmake'
      dbus-gmain| Found CMake: NO
      dbus-gmain| Run-time dependency dbus-1 found: NO (tried pkgconfig)
      
      ../subprojects/dbus-gmain/meson.build:107:11: ERROR: Dependency "dbus-1" not found, tried pkgconfig
      
      A full log can be found at /tmp/pip-install-4umkat69/dbus-python_e340cafd355445b5b3b3e8f6933865ea/.mesonpy-w5lbswi8/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by pblanton** [comment]
Python 3.10.12 FYI

**Comment by pblanton** [comment]
Fixed!!

For Ubuntu 24.04 LTS you also need...

`sudo apt install build-essential libpython3-dev libdbus-1-dev`

**Comment by pblanton** [comment]
App still won't run, but that took care of the dbus error.

I now get ...
```

(.venv) pblanton@ThreadRipper:~/Downloads/StreamController$ python3 main.py
2024-10-09 11:56:18.012 | INFO     | globals:<module>:39 - Creating data path: /home/pblanton/.var/app/com.core447.StreamController/data
Traceback (most recent call last):
  File "/home/pblanton/Downloads/StreamController/main.py", line 34, in <module>
    from src.app import App
  File "/home/pblanton/Downloads/StreamController/src/app.py", line 35, in <module>
    from src.windows.mainWindow.mainWindow import MainWindow
  File "/home/pblanton/Downloads/StreamController/src/windows/mainWindow/mainWindow.py", line 32, in <module>
    from src.windows.mainWindow.elements.Sidebar.Sidebar import Sidebar
  File "/home/pblanton/Downloads/StreamController/src/windows/mainWindow/elements/Sidebar/Sidebar.py", line 21, in <module>
    from src.windows.mainWindow.elements.PageSelector import PageSelector
  File "/home/pblanton/Downloads/StreamController/src/windows/mainWindow/elements/PageSelector.py", line 30, in <module>
    from src.windows.PageManager.PageManager import PageManager
  File "/home/pblanton/Downloads/StreamController/src/windows/PageManager/PageManager.py", line 25, in <module>
    from src.windows.PageManager.elements.PageSelector import PageSelector
  File "/home/pblanton/Downloads/StreamController/src/windows/PageManager/elements/PageSelector.py", line 40, in <module>
    class PageSelector(Adw.NavigationPage):
  File "/home/pblanton/Downloads/StreamController/.venv/lib/python3.10/site-packages/gi/module.py", line 130, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Adw' object has no attribute 'NavigationPage'
```

**Comment by pblanton** [comment]
Adw does in fact have no "NavigationPage" element...

![Screenshot from 2024-10-09 12-03-49](https://github.com/user-attachments/assets/59458692-caa5-4c34-995d-cad4631672d2)

**Comment by pblanton** [comment]
I'm giving up for now, as I have other work to do. I just thought that I'd try to get my StreamDeck set up this morning.

**Comment by G4PLS** [comment]
The Adw package you have installed is probably "outdated". Sadly i dont know the package name for this fix anymore

**Comment by Core447** [comment]
> The Adw package you have installed is probably "outdated". Sadly i dont know the package name for this fix anymore

Yes, but you can just use the Flatpak to avoid this issue.

**Comment by Core447** [comment]
Gonna close this because there's nothing I can do to about the outdated adw.
