### ISSUE TITLE
BUG Run Command on Dial only  works once

### ISSUE THREAD

**Issue by hoferbeck** [StreamController/StreamController#294]
**Describe the bug**
When "Run Command" is bound to a Dial from a streamdeck plus it only works oce

**To Reproduce**
Add Action at Dial -> OS -> Run Command
Assign Dial Turn CW  or CCW to "Key Down"
Turn dial, then the command is executed once but not again, until I restart Streamcontroller 
When the Command is bound to a Key it works like expected
This Error shows up in the Terminal
```
Exception ignored in: <function _after_fork at 0x7fa6a8d951c0>
Traceback (most recent call last):
  File "/nix/store/px2nj16i5gc3d4mnw5l1nclfdxhry61p-python3-3.12.7/lib/python3.12/threading.py", line 1699, in _after_fork
    thread._stop()
TypeError: 'bool' object is not callable
```
**Expected behavior**
Execute Multiple Times

**Screenshots**
![Screenshot_20241207_182525](https://github.com/user-attachments/assets/97377841-86bd-4395-b224-ae51d66173d6)

**Additional context**
Im using a NixOS unstable as my Distro, and the nixpkgs and the Flatpak is affeted
I found a Workaround, to just use the "Easy Run Command" as it works without any issues

Please only post issues to this repository that are directly related to the application itself, not a plugin.

**Comment by ImDevinC** [comment]
@hoferbeck does this still happen on the latest release? If so, can you please provide logs from when it happens

**Comment by hoferbeck** [comment]
I just installed the latest flatpak release (normally i use the Nixos release) but i still get the same error as before 

```Exception ignored in: <function _after_fork at 0x7fcb60153d80>
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1699, in _after_fork
    thread._stop()
TypeError: 'bool' object is not callable
```

**Comment by ImDevinC** [comment]
Can you please provide the full log from StreamController. This can be done by reproducing the issue, and then goign to Settings -> About -> Troubleshooting -> Diagnostics... and choosing Save As to save the file

**Comment by hoferbeck** [comment]
Here is the log file: 

[StreamController.log](https://github.com/user-attachments/files/21006583/StreamController.log)

**Comment by ImDevinC** [comment]
I don't see the error you're describing, but I do see this:
It looks like for some reason it'se sending `+5` instead of just 5. Is this a configurable value in the plugin?

To reproduce the original error, can you please close StreamController, start it again, and then reproduce the issue before generating logs? Thanks

```
  File "/app/bin/StreamController/GtkHelper/ScaleRow.py", line 54, in __init__
    self._adjustment = Gtk.Adjustment.new(value, min, max, step, 1, 0)
    │                  │   │          │   │      │    │    └ 1
    │                  │   │          │   │      │    └ 255
    │                  │   │          │   │      └ -225
    │                  │   │          │   └ '+5'
    │                  │   │          └ <classmethod(gi.FunctionInfo(new))>
    │                  │   └ <class 'gi.overrides.Gtk.Adjustment'>
    │                  └ <OverridesProxyModule <IntrospectionModule 'Gtk' from '/usr/lib/x86_64-linux-gnu/girepository-1.0/Gtk-4.0.typelib'>>
    └ <ScaleRow.ScaleRow object at 0x7f679c2850c0 (GtkHelper+ScaleRow+ScaleRow at 0x556d6d7ac130)>

TypeError: Must be number, not str
```

**Comment by hoferbeck** [comment]
This is the command Im using trying to execute ```/run/current-system/sw/bin/pactl set-sink-volume @DEFAULT_SINK@ +5%```
(Make the Default Sound Output device 5% louder)
I Closed StreamController and reopened it to reproduce the error (as since when the dial is turned once, it dosn't work anymore)

**Comment by AlainGyger** [comment]
I'm getting the same error, when using a "Run Command" action. The About -> Troubleshooting -> Diagnostics file doesn't show the error but syslog does:

com.core447.StreamController.desktop[741842]: Exception ignored in: <function _after_fork at 0x74be36d1bd80>
com.core447.StreamController.desktop[741842]: Traceback (most recent call last):
com.core447.StreamController.desktop[741842]:   File "/usr/lib/python3.12/threading.py", line 1699, in _after_fork
com.core447.StreamController.desktop[741842]:     thread._stop()
com.core447.StreamController.desktop[741842]: TypeError: 'bool' object is not callable

Running version 1.5.0-beta.11 from flatpak

**Comment by ImDevinC** [comment]
@AlainGyger what command are you trying to run? I don't have a deck with dials so I can't reproduce unfortunately, so just trying to see what else I can do to troubleshoot

**Comment by AlainGyger** [comment]
I'm running a custom python program and I'm using a StreamDeck XL.

**Comment by AlainGyger** [comment]
I just turned off the "Detached" option and I don't get the error anymore.

**Comment by ImDevinC** [comment]
Closing as this looks to be resolved. If I'm mistaken, feel free to comment and we can re-open
