### ISSUE TITLE
BUG: Crash on launch with missing pulseaudio device

### ISSUE THREAD

**Issue by joshrivers** [StreamController/StreamController#296]
**Describe the bug**
Application will not launch with missing Pulseaudio device

**To Reproduce**
1. `flatpak run com.core447.StreamController`
2. Application window flashes and disappears
3. Process stops

**Expected behavior**
Application should launch

**Screenshots**
N/A

**Additional context**

Stderr Output
```
2024-12-09 15:22:16.812 | WARNING  | __main__:main:249 - Should you get an Error 71 (Protocol error) please add GSK_RENDERER=ngl to your "/etc/environment" file
2024-12-09 15:22:16.812 | INFO     | __main__:quit_running:192 - Checking if another instance is running
2024-12-09 15:22:16.813 | INFO     | __main__:quit_running:200 - No other instance running, continuing
2024-12-09 15:22:16.813 | ERROR    | __main__:quit_running:201 - org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
2024-12-09 15:22:17.065 | ERROR    | src.backend.GnomeExtensions:connect_dbus:31 - Failed to connect to D-Bus: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
2024-12-09 15:22:17.066 | INFO     | src.backend.PageManagement.PageManagerBackend:update_auto_change_info:333 - Updated auto-change info in 6.270408630371094e-05 seconds
2024-12-09 15:22:17.066 | INFO     | src.backend.PageManagement.PageManagerBackend:remove_old_backups:448 - Removed old page backups: 2024-12-09T15:12:37.985769
2024-12-09 15:22:17.227 | INFO     | src.backend.PluginManager.PluginBase:launch_backend:524 - Launching backend: . /home/josh/.var/app/com.core447.StreamController/data/plugins/com_core447_OBSPlugin/backend/.venv/bin/activate && python3 /home/josh/.var/app/com.core447.StreamController/data/plugins/com_core447_OBSPlugin/backend/backend.py --port=32873
2024-12-09 15:22:17.280 | SUCCESS  | streamcontroller_plugin_tools.BackendBase:start_server:33 - Started server
2024-12-09 15:22:17.282 | DEBUG    | OBSController:connect_to:30 - Trying to connect to obs with legacy: False
2024-12-09 15:22:17.283 | INFO     | OBSController:connect_to:34 - Successfully connected to OBS
2024-12-09 15:22:19.355 | TRACE    | src.backend.PageManagement.PageManagerBackend:register_page:272 - Registering page: /home/josh/.var/app/com.core447.StreamController/data/plugins/com_core447_VolumeMixer/pages/VolumeMixer.json
2024-12-09 15:22:19.355 | INFO     | src.backend.PageManagement.PageManagerBackend:update_auto_change_info:333 - Updated auto-change info in 0.00012564659118652344 seconds
2024-12-09 15:22:19.355 | TRACE    | src.backend.PageManagement.PageManagerBackend:register_page:272 - Registering page: /home/josh/.var/app/com.core447.StreamController/data/plugins/com_core447_VolumeMixer/pages/VolumeMixerSDPlus.json
2024-12-09 15:22:19.355 | INFO     | src.backend.PageManagement.PageManagerBackend:update_auto_change_info:333 - Updated auto-change info in 0.00010085105895996094 seconds
2024-12-09 15:22:19.380 | ERROR    | src.backend.WindowGrabber.WindowGrabber:init_integration:60 - Unsupported environment: kde with server: wayland for window grabber.
2024-12-09 15:22:19.391 | INFO     | __main__:load:92 - Loading app
2024-12-09 15:22:19.400 | INFO     | src.backend.Store.StoreBackend:get_stores:74 - Official store branch: main
2024-12-09 15:22:19.403 | INFO     | src.backend.DeckManagement.DeckManager:__init__:66 - Running under Flatpak. Using separate thread to detect device disconnection.
2024-12-09 15:22:19.403 | INFO     | src.backend.DeckManagement.DeckManager:__init__:70 - Beta resume mode: True
2024-12-09 15:22:19.448 | INFO     | src.backend.Store.StoreBackend:get_stores:74 - Official store branch: main
2024-12-09 15:22:19.469 | INFO     | src.backend.PluginManager.ActionBase:__init__:79 - Loaded action Mute with id com_gapls_AudioControl::Mute
2024-12-09 15:22:19.469 | INFO     | src.backend.PluginManager.ActionBase:__init__:79 - Loaded action Digital clock with id com_core447_Clocks::DigitalClock
2024-12-09 15:22:19.469 | INFO     | src.backend.PluginManager.ActionBase:__init__:79 - Loaded action CPU Usage with id com_core447_OSPlugin::CPU
2024-12-09 15:22:19.469 | INFO     | src.backend.PluginManager.ActionBase:__init__:79 - Loaded action Easy Run Command with id com_core447_OSPlugin::EasyCommand
2024-12-09 15:22:19.469 | INFO     | src.backend.PluginManager.ActionBase:__init__:79 - Loaded action Easy Run Command with id com_core447_OSPlugin::EasyCommand
2024-12-09 15:22:19.469 | DEBUG    | src.backend.PageManagement.Page:load:78 - Loaded page Main in 0.00 seconds
2024-12-09 15:22:19.470 | INFO     | src.backend.DeckManagement.DeckController:load_page:676 - Loading page Main on deck A00TA4052K43UW
2024-12-09 15:22:19.559 | ERROR    | plugins.com_gapls_AudioControl.internal.PulseHelpers:get_device:64 - Error while getting device: alsa_output.usb-R__DE_R__DECaster_Duo-00.analog-stereo with filter: sink. Error: alsa_output.usb-R__DE_R__DECaster_Duo-00.analog-stereo
2024-12-09 15:22:19.559 | ERROR    | src.backend.DeckManagement.DeckController:load_page:699 - An error has been caught in function 'load_page', process 'MainProcess' (3), thread 'MainThread' (139928341161792):
Traceback (most recent call last):

  File "/home/josh/.var/app/com.core447.StreamController/data/plugins/com_gapls_AudioControl/internal/PulseHelpers.py", line 60, in get_device
    return pulse.get_sink_by_name(pulse_device_name)
           │     │                └ 'alsa_output.usb-R__DE_R__DECaster_Duo-00.analog-stereo'
           │     └ <function Pulse._pulse_get_list.<locals>._wrapper_method at 0x7f4328967600>
           └ <pulsectl.pulsectl.Pulse object at 0x7f432086d520>

  File "/app/lib/python3.12/site-packages/pulsectl/pulsectl.py", line 567, in _wrapper_method
    if not data: raise PulseIndexError(index)
           │           │               └ 'alsa_output.usb-R__DE_R__DECaster_Duo-00.analog-stereo'
           │           └ <class 'pulsectl.pulsectl.PulseIndexError'>
           └ []

pulsectl.pulsectl.PulseIndexError: alsa_output.usb-R__DE_R__DECaster_Duo-00.analog-stereo


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/app/bin/StreamController/main.py", line 277, in <module>
    main()
    └ <function main at 0x7f4329d9b100>

  File "/app/bin/StreamController/main.py", line 274, in main
    load()
    └ <function load at 0x7f4329d9a020>

  File "/app/bin/StreamController/main.py", line 94, in load
    gl.deck_manager.load_decks()
    │  │            └ <function DeckManager.load_decks at 0x7f432ffdc540>
    │  └ <src.backend.DeckManagement.DeckManager.DeckManager object at 0x7f43221b39b0>
    └ <module 'globals' from '/app/bin/StreamController/globals.py'>

  File "/app/bin/StreamController/src/backend/DeckManagement/DeckManager.py", line 78, in load_decks
    self.load_hardware_decks()
    │    └ <function DeckManager.load_hardware_decks at 0x7f432ffdcd60>
    └ <src.backend.DeckManagement.DeckManager.DeckManager object at 0x7f43221b39b0>

  File "/app/bin/StreamController/src/backend/DeckManagement/DeckManager.py", line 94, in load_hardware_decks
    deck_controller = DeckController(self, deck)
                      │              │     └ <StreamDeck.Devices.StreamDeckOriginalV2.StreamDeckOriginalV2 object at 0x7f432082da30>
                      │              └ <src.backend.DeckManagement.DeckManager.DeckManager object at 0x7f43221b39b0>
                      └ <class 'src.backend.DeckManagement.DeckController.DeckController'>

  File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 393, in __init__
    self.load_default_page()
    │    └ <function DeckController.load_default_page at 0x7f434413b9c0>
    └ <src.backend.DeckManagement.DeckController.DeckController object at 0x7f432082dac0>

  File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 524, in load_default_page
    self.load_page(page)
    │    │         └ <src.backend.PageManagement.Page.Page object at 0x7f4320801df0>
    │    └ <function DeckController.load_page at 0x7f4344160f40>
    └ <src.backend.DeckManagement.DeckController.DeckController object at 0x7f432082dac0>

> File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 699, in load_page
    self.active_page.call_actions_ready_and_set_flag()
    │    │           └ <function Page.call_actions_ready_and_set_flag at 0x7f43417f2200>
    │    └ <src.backend.PageManagement.Page.Page object at 0x7f4320801df0>
    └ <src.backend.DeckManagement.DeckController.DeckController object at 0x7f432082dac0>

  File "/app/bin/StreamController/src/backend/PageManagement/Page.py", line 548, in call_actions_ready_and_set_flag
    action.on_ready()
    │      └ <function Mute.on_ready at 0x7f4322154b80>
    └ <plugins.com_gapls_AudioControl.actions.Mute.Mute object at 0x7f4320864b90>

  File "/home/josh/.var/app/com.core447.StreamController/data/plugins/com_gapls_AudioControl/actions/Mute.py", line 19, in on_ready
    super().on_ready()

  File "/home/josh/.var/app/com.core447.StreamController/data/plugins/com_gapls_AudioControl/actions/DeviceBase.py", line 353, in on_ready
    self.load_settings()
    │    └ <function DeviceBase.load_settings at 0x7f4322137100>
    └ <plugins.com_gapls_AudioControl.actions.Mute.Mute object at 0x7f4320864b90>

  File "/home/josh/.var/app/com.core447.StreamController/data/plugins/com_gapls_AudioControl/actions/DeviceBase.py", line 152, in load_settings
    device = get_device(self.device_filter, self.pulse_device_name)
             │          │    │              │    └ 'alsa_output.usb-R__DE_R__DECaster_Duo-00.analog-stereo'
             │          │    │              └ <plugins.com_gapls_AudioControl.actions.Mute.Mute object at 0x7f4320864b90>
             │          │    └ <DeviceFilter.SINK: 'sink'>
             │          └ <plugins.com_gapls_AudioControl.actions.Mute.Mute object at 0x7f4320864b90>
             └ <function get_device at 0x7f4322134180>

  File "/home/josh/.var/app/com.core447.StreamController/data/plugins/com_gapls_AudioControl/internal/PulseHelpers.py", line 65, in get_device
    raise PulseError
          └ <class 'plugins.com_gapls_AudioControl.internal.PulseHelpers.PulseError'>

plugins.com_gapls_AudioControl.internal.PulseHelpers.PulseError
2024-12-09 15:22:19.562 | INFO     | src.backend.DeckManagement.DeckController:load_page:707 - Loaded page Main on deck A00TA4052K43UW
2024-12-09 15:22:19.585 | INFO     | src.backend.DeckManagement.DeckController:load_background:528 - Loading background in thread: 139926007969472

(process:3): Gtk-WARNING **: 15:22:19.585: Theme parser error: style.css:399:19-27: Unknown name of pseudo-class
2024-12-09 15:22:19.621 | INFO     | src.backend.Store.StoreBackend:get_stores:74 - Official store branch: main
2024-12-09 15:22:19.631 | ERROR    | plugins.com_gapls_AudioControl.internal.PulseHelpers:get_device:64 - Error while getting device: alsa_output.usb-R__DE_R__DECaster_Duo-00.analog-stereo with filter: sink. Error: alsa_output.usb-R__DE_R__DECaster_Duo-00.analog-stereo
2024-12-09 15:22:19.632 | ERROR    | src.backend.DeckManagement.DeckController:run:89 - An error has been caught in function 'run', process 'MainProcess' (3), thread 'MediaPlayerThread' (139926007969472):
Traceback (most recent call last):

  File "/home/josh/.var/app/com.core447.StreamController/data/plugins/com_gapls_AudioControl/internal/PulseHelpers.py", line 60, in get_device
    return pulse.get_sink_by_name(pulse_device_name)
           │     │                └ 'alsa_output.usb-R__DE_R__DECaster_Duo-00.analog-stereo'
           │     └ <function Pulse._pulse_get_list.<locals>._wrapper_method at 0x7f4328967600>
           └ <pulsectl.pulsectl.Pulse object at 0x7f4320866cf0>

  File "/app/lib/python3.12/site-packages/pulsectl/pulsectl.py", line 567, in _wrapper_method
    if not data: raise PulseIndexError(index)
           │           │               └ 'alsa_output.usb-R__DE_R__DECaster_Duo-00.analog-stereo'
           │           └ <class 'pulsectl.pulsectl.PulseIndexError'>
           └ []

pulsectl.pulsectl.PulseIndexError: alsa_output.usb-R__DE_R__DECaster_Duo-00.analog-stereo


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1032, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f439a51a480>
    └ <MediaPlayerThread(MediaPlayerThread, started daemon 139926007969472)>
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
    │    └ <function MediaPlayerThread.run at 0x7f434413a5c0>
    └ <MediaPlayerThread(MediaPlayerThread, started daemon 139926007969472)>

  File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 213, in run
    self.perform_media_player_tasks()
    │    └ <function MediaPlayerThread.perform_media_player_tasks at 0x7f434413aca0>
    └ <MediaPlayerThread(MediaPlayerThread, started daemon 139926007969472)>

  File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 298, in perform_media_player_tasks
    task.run()
    │    └ <function MediaPlayerTask.run at 0x7f43441d0cc0>
    └ MediaPlayerTask(deck_controller=<src.backend.DeckManagement.DeckController.DeckController object at 0x7f432082dac0>, page=<sr...

> File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 89, in run
    self._callable(*self.args, **self.kwargs)
    │    │          │    │       │    └ {'update': False}
    │    │          │    │       └ MediaPlayerTask(deck_controller=<src.backend.DeckManagement.DeckController.DeckController object at 0x7f432082dac0>, page=<sr...
    │    │          │    └ (<src.backend.PageManagement.Page.Page object at 0x7f4320801df0>,)
    │    │          └ MediaPlayerTask(deck_controller=<src.backend.DeckManagement.DeckController.DeckController object at 0x7f432082dac0>, page=<sr...
    │    └ <bound method DeckController.load_all_inputs of <src.backend.DeckManagement.DeckController.DeckController object at 0x7f43208...
    └ MediaPlayerTask(deck_controller=<src.backend.DeckManagement.DeckController.DeckController object at 0x7f432082dac0>, page=<sr...

  File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 613, in load_all_inputs
    future.result()
    │      └ <function Future.result at 0x7f439a34a340>
    └ <Future at 0x7f4320801610 state=finished raised PulseError>

  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           └ None
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
          └ None
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │        │            └ None
             │        └ None
             └ None

  File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 623, in load_input
    controller_input.load_from_input_dict(input_dict, update)
    │                │                    │           └ False
    │                │                    └ {'states': {'0': {'media': {'path': None}, 'actions': [{'id': 'com_gapls_AudioControl::Mute', 'settings': {'pulse-name': 'als...
    │                └ <function ControllerKey.load_from_input_dict at 0x7f434416a020>
    └ <src.backend.DeckManagement.DeckController.ControllerKey object at 0x7f43221b2f60>

  File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 2025, in load_from_input_dict
    state.own_actions_update() # Why not threaded? Because this would mean that some image changing calls might get executed after the next lines which blocks custom assets
    │     └ <function ControllerInputState.own_actions_update at 0x7f43441680e0>
    └ <src.backend.DeckManagement.DeckController.ControllerKeyState object at 0x7f432082db80>

  File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 1534, in own_actions_update
    action.on_update()
    │      └ <function ActionBase.on_update at 0x7f43417cd760>
    └ <plugins.com_gapls_AudioControl.actions.Mute.Mute object at 0x7f4320864b90>

  File "/app/bin/StreamController/src/backend/PluginManager/ActionBase.py", line 135, in on_update
    self.on_ready() # backward compatibility
    │    └ <function Mute.on_ready at 0x7f4322154b80>
    └ <plugins.com_gapls_AudioControl.actions.Mute.Mute object at 0x7f4320864b90>

  File "/home/josh/.var/app/com.core447.StreamController/data/plugins/com_gapls_AudioControl/actions/Mute.py", line 19, in on_ready
    super().on_ready()

  File "/home/josh/.var/app/com.core447.StreamController/data/plugins/com_gapls_AudioControl/actions/DeviceBase.py", line 353, in on_ready
    self.load_settings()
    │    └ <function DeviceBase.load_settings at 0x7f4322137100>
    └ <plugins.com_gapls_AudioControl.actions.Mute.Mute object at 0x7f4320864b90>

  File "/home/josh/.var/app/com.core447.StreamController/data/plugins/com_gapls_AudioControl/actions/DeviceBase.py", line 152, in load_settings
    device = get_device(self.device_filter, self.pulse_device_name)
             │          │    │              │    └ 'alsa_output.usb-R__DE_R__DECaster_Duo-00.analog-stereo'
             │          │    │              └ <plugins.com_gapls_AudioControl.actions.Mute.Mute object at 0x7f4320864b90>
             │          │    └ <DeviceFilter.SINK: 'sink'>
             │          └ <plugins.com_gapls_AudioControl.actions.Mute.Mute object at 0x7f4320864b90>
             └ <function get_device at 0x7f4322134180>

  File "/home/josh/.var/app/com.core447.StreamController/data/plugins/com_gapls_AudioControl/internal/PulseHelpers.py", line 65, in get_device
    raise PulseError
          └ <class 'plugins.com_gapls_AudioControl.internal.PulseHelpers.PulseError'>

plugins.com_gapls_AudioControl.internal.PulseHelpers.PulseError
2024-12-09 15:22:19.639 | DEBUG    | src.backend.DeckManagement.DeckController:update_all_inputs:438 - Updating all inputs took 0.0043337345123291016 seconds
2024-12-09 15:22:19.640 | TRACE    | src.app:on_activate:80 - running: on_activate
2024-12-09 15:22:19.640 | TRACE    | src.windows.mainWindow.mainWindow:build:93 - Building main window
2024-12-09 15:22:19.759 | SUCCESS  | src.app:on_activate:112 - Finished loading app
2024-12-09 15:22:19.760 | INFO     | autostart:request_background_callback:57 - request_background success=True
Gdk-Message: 15:22:19.761: Lost connection to Wayland compositor.
2024-12-09 15:22:19.851 | INFO     | streamcontroller_plugin_tools.BackendBase:on_disconnect:39 - Connection closed
```

**Comment by G4PLS** [comment]
Should be fixed with https://github.com/G4PLS/AudioControl/commit/507ff057c9f7a38a8d4ef35d0294656ba294d328
Awaiting merge in https://github.com/StreamController/StreamController-Store/pull/73

**Comment by Core447** [comment]
> Awaiting merge in [StreamController/StreamController-Store#73](https://github.com/StreamController/StreamController-Store/pull/73)

Merged it.
