### ISSUE TITLE
Command launch Plugin is gone?!

### ISSUE THREAD

**Issue by D1Ck3n** [StreamController/StreamController#302]
Hi there,

i was super happy with this tool but since today i cannot use the plugin to monitor CPU and RAM and launch commands. Are they removed? the buttons have a dot on it and it shows "Install missing plugin".

where do i get them now?

best 
D1Ck3n

**Comment by Core447** [comment]
There was an update for the OS plugin, maybe that broke something. Can you please try to reinstall it via the store?

If this doesn't work, please close the app completely (via the option in the hamburger menu), start it from the terminal (`flatpak run com.core447.StreamController`) and share the logs.

**Comment by D1Ck3n** [comment]
Hi @Core447, 

I first tried to reinstall the plugin, but that didn't work. 

If I close the app completely via the menu, but it cannot be started via the terminal:

```
flatpak run com.core447.StreamController                         ✔ 
2024-12-25 19:38:20.339 | WARNING  | __main__:main:249 - Should you get an Error 71 (Protocol error) please add GSK_RENDERER=ngl to your "/etc/environment" file
2024-12-25 19:38:20.340 | INFO     | __main__:quit_running:192 - Checking if another instance is running
2024-12-25 19:38:20.610 | ERROR    | __main__:<module>:277 - An error has been caught in function '<module>', process 'MainProcess' (3), thread 'MainThread' (135088231651136):
Traceback (most recent call last):

> File "/app/bin/StreamController/main.py", line 277, in <module>
    main()
    └ <function main at 0x7adc32fad6c0>

  File "/app/bin/StreamController/main.py", line 255, in main
    quit_running()
    └ <function quit_running at 0x7adc32fad4e0>

  File "/app/bin/StreamController/main.py", line 217, in quit_running
    action_interface.Activate("reopen", [], [])
    └ <Interface <ProxyObject wrapping <dbus._dbus.SessionBus (session) at 0x7adc32f6a1b0> :1.90 /com/core447/StreamController at 0...

  File "/app/lib/python3.12/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
           │    │              │       └ {}
           │    │              └ ('reopen', [], [])
           │    └ <dbus.proxies._ProxyMethod object at 0x7adc337c88c0>
           └ <dbus.proxies._DeferredMethod object at 0x7adc5405fb30>

  File "/app/lib/python3.12/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
           │    │           │             │    └ dbus.String(':1.90')
           │    │           │             └ <dbus.proxies._ProxyMethod object at 0x7adc337c88c0>
           │    │           └ <function Connection.call_blocking at 0x7adcac7fce00>
           │    └ <dbus._dbus.SessionBus (session) at 0x7adc32f6a1b0>
           └ <dbus.proxies._ProxyMethod object at 0x7adc337c88c0>

  File "/app/lib/python3.12/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    │    └ <method 'send_message_with_reply_and_block' of '_dbus_bindings.Connection' objects>
                    └ <dbus._dbus.SessionBus (session) at 0x7adc32f6a1b0>

dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Remote peer disconnected
```

BUT: closing it completely and restarting it solved the problem!

now I can use it normally again! :) 

Thanks for the hint!

**Comment by Core447** [comment]
> now I can use it normally again! :)
> 
> Thanks for the hint!

Np, I'm glad you got it working again!
