### ISSUE TITLE
BUG: 1.4.10-beta doesn't find stream deck on debian12

### ISSUE THREAD

**Issue by FreeBSD-fan** [StreamController/StreamController#50]
BUG: 1.4.10-beta doesn't find stream deck on debian12
1.4.11-beta works on same system, but running cinnamon mint.

**Comment by FreeBSD-fan** [comment]
Have 1.4.11-beta on Mint (Cinnamon), kde neon, and debian12.
Works only on Mint so far.
Not on KDE Neon 6.0 either.

`Operating System: KDE neon 6.0
KDE Plasma Version: 6.0.3
KDE Frameworks Version: 6.0.0
Qt Version: 6.7.0
Kernel Version: 6.5.0-27-generic (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i3-7100 CPU @ 3.90GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630
Manufacturer: Dell Inc.
Product Name: Inspiron 3668`

**Comment by Core447** [comment]
As mentioned in #31, it would be nice if you could test the examples provided by the python library I use: https://github.com/abcminiuser/python-elgato-streamdeck. I'll try Debian myself and report back.

**Comment by Core447** [comment]
I have tested StreamController on a fresh Debian 12 installation and it works fine:
![image](https://github.com/StreamController/StreamController/assets/100139110/2a37a999-d99b-4f66-a312-18f719510784)

**Comment by FreeBSD-fan** [comment]
I am not python literate, but I saved your script as discovery and ran it.
`Found 1 Stream Deck(s).

Traceback (most recent call last):
  File "/media/steven/Configs/StreamController/examples/./discovery", line 64, in <module>
    print_deck_info(index, deck)
  File "/media/steven/Configs/StreamController/examples/./discovery", line 19, in print_deck_info
    touchscreen_image_format = deck.touchscreen_image_format()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'StreamDeckOriginal' object has no attribute 'touchscreen_image_format'
python3: ../../libusb/os/threads_posix.h:58: usbi_mutex_destroy: Assertion `pthread_mutex_destroy(mutex) == 0' failed.
Aborted (core dumped)
`

I must be missing some package.  I created a script to install packages:

`# install streamcontroller and dependencies
sudo wget https://raw.githubusercontent.com/streamdeck-linux-gui/streamdeck-linux-gui/main/udev/60-streamdeck.rules -O /etc/udev/rules.d/60-streamdeck.rules
sudo tee /etc/udev/rules.d/10-streamdeck.rules << EOF
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0fd9", GROUP="users", TAG+="uaccess"
EOF
sudo udevadm control --reload-rules
sudo udevadm trigger
sudo apt install -y python3-pip
sudo apt install -y python3-setuptools
sudo apt install -y libudev-dev
sudo apt install -y libusb-1.0-0-dev
sudo apt install -y libhidapi-libusb0
sudo apt install -y libjpeg-dev
sudo apt install -y zlib1g-dev
sudo apt install -y libopenjp2-7
sudo apt install -y python3-libtiff
sudo apt install -y python3-wheel
sudo apt install -y python3-pillow
sudo apt install -y python3-elgato-streamdeck
sudo apt install -y streamdeck-ui
`

**Comment by FreeBSD-fan** [comment]
Did I format that wrong?  Should I have  quoted it, instead of marking it as code?

**Comment by FreeBSD-fan** [comment]
I ran into a dependency problem when installing from github:
https://streamcontroller.github.io/docs/latest/installation/
  dbus-gmain| Found pkg-config: YES (/usr/bin/pkg-config) 0.29.2
      dbus-gmain| Found CMake: /usr/bin/cmake (3.22.1)
      dbus-gmain| Run-time dependency dbus-1 found: NO (tried pkgconfig and cmake)
      
      ../subprojects/dbus-gmain/meson.build:107:11: ERROR: Dependency "dbus-1" not found, tried pkgconfig and cmake
      
      A full log can be found at /tmp/pip-install-j5alh16a/dbus-python_fa3520348c404b65bf706183be969d75/.mesonpy-djw6jncm/meson-logs/meson-log.txt
      [end of output]

There's no such log and I tried to install using sudo apt install dbus-1 (also dbus-python) to no avail.

**Comment by FreeBSD-fan** [comment]
I am doing this Installation on Mint (because stream deck works on it) and I'm trying to get your examples to work.
discovery works, basic fails due missing Released.png

**Comment by Core447** [comment]
Here are all the commands:

1. `git clone https://github.com/abcminiuser/python-elgato-streamdeck.git`.
2. `cd python-elgato-streamdeck`.
3. `cd src`.
4. `python -m venv .venv`.
5. `source .venv/bin/activate`.
6. `pip install Pillow`.
7. `python3 example_basic.py`.

StreamController works for you on Mint, right? It would be best to test it on a system where StreamController doesn't work.
And sorry for the inconvenience!

**Comment by FreeBSD-fan** [comment]
Ok, I tried this under kde neon (where I haven't gotten stream deck to detect my deck yet.
I dont know if I should tag the next block as Code or Quote:
python3 example_basic.py
Found 1 Stream Deck(s).

Traceback (most recent call last):
  File "/home/steven/python-elgato-streamdeck/src/example_basic.py", line 117, in <module>
    deck.open()
  File "/home/steven/python-elgato-streamdeck/src/StreamDeck/Devices/StreamDeck.py", line 214, in open
    self.device.open()
  File "/home/steven/python-elgato-streamdeck/src/StreamDeck/Transport/LibUSBHIDAPI.py", line 373, in open
    self.device_handle = self.hidapi.open_device(self.device_info['path'])
  File "/home/steven/python-elgato-streamdeck/src/StreamDeck/Transport/LibUSBHIDAPI.py", line 224, in open_device
    raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.

What am I missing?  Also, during step 4 (python -m venv .venv) I had to change it to python3.  
I did install libhidapi-libusb0

**Comment by Core447** [comment]
> I dont know if I should tag the next block as Code or Quote:

Code, I believe

Does [streamdeck-linux-gui](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui) work on your kde neon install? It is using the same library in the background.

> StreamDeck.Transport.Transport.TransportError: Could not open HID device.

Seams like the library is not allowed to open the deck. Have you added the udev rules I mentioned in #31 ([comment](https://github.com/StreamController/StreamController/issues/31#issuecomment-2053628819))?

**Comment by FreeBSD-fan** [comment]
./streamcontroller.sh 
--2024-04-17 10:03:26--  https://raw.githubusercontent.com/streamdeck-linux-gui/streamdeck-linux-gui/main/udev/60-streamdeck.rules
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8001::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 615 [text/plain]
Saving to: ‘/etc/udev/rules.d/60-streamdeck.rules’

/etc/udev/rules.d/60-stream 100%[=========================================>]     615  --.-KB/s    in 0.001s  

2024-04-17 10:03:27 (1.06 MB/s) - ‘/etc/udev/rules.d/60-streamdeck.rules’ saved [615/615]

SUBSYSTEMS=="usb", ATTRS{idVendor}=="0fd9", GROUP="users", TAG+=

I created a script and run it on each distro I boot.

**Comment by FreeBSD-fan** [comment]
cat /etc/udev/rules.d/60-streamdeck.rules 
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0080", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0084", TAG+="uaccess"
KERNEL=="uinput", SUBSYSTEM=="misc", OPTIONS+="static_node=uinput", TAG+="uaccess", GROUP="input", MODE="0660"

**Comment by FreeBSD-fan** [comment]
sudo apt install streamdeck-linux-gui
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package streamdeck-linux-gui

It seems neon is unaware of streamdeck-linux-gui...

**Comment by Core447** [comment]
The installation instructions of streamdeck-linux-gui for Debian based systems can be found [here](https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/blob/main/docs/installation/ubuntu.md)

**Comment by FreeBSD-fan** [comment]
OK, I got streamdeck-linux-gui working on kde neon.  Your discovery script wprked (after a usbreset 'stream deck'
./discovery 
Found 1 Stream Deck(s).

Deck 0 - Stream Deck Original.
         - ID: 1-4:1.0
         - Serial: 'AL44H1C03513'
         - Firmware Version: '1.0.191203'
         - Key Count: 15 (in a 3x5 grid)
         - Key Images: 72x72 pixels, BMP format, rotated 0 degrees, mirrored horizontally/vertically

but basic failed:

./basic 
Found 1 Stream Deck(s).

Opened 'Stream Deck Original' device (serial number: 'AL44H1C03513', fw: '1.0.191203')
Traceback (most recent call last):
  File "/media/steven/Configs/StreamController/examples/./basic", line 129, in <module>
    update_key_image(deck, key, False)
  File "/media/steven/Configs/StreamController/examples/./basic", line 73, in update_key_image
    image = render_key_image(deck, key_style["icon"], key_style["font"], key_style["label"])
  File "/media/steven/Configs/StreamController/examples/./basic", line 30, in render_key_image
    icon = Image.open(icon_filename)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2953, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/media/steven/Configs/StreamController/examples/./Assets/Released.png'
python3: ../../libusb/os/threads_posix.h:58: usbi_mutex_destroy: Assertion `pthread_mutex_destroy(mutex) == 0' failed.
Aborted

It seems I'm missing a package containing Released.png

**Comment by FreeBSD-fan** [comment]
I was trying to follow instructions at:
https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/blob/main/docs/installation/source.md
and got this error trying to clone the project:
git clone <https://github.com/streamdeck-linux-gui/streamdeck-linux-gui.git>
bash: syntax error near unexpected token `newline'

**Comment by Core447** [comment]
> It seems I'm missing a package containing Released.png

You have to make sure that you're in the `src` dir

> Your discovery script wprked (after a usbreset 'stream deck'

Ok, great - Just to clarify, this is not my script, but the one from the library I use

And StreamController is still not starting on KDE neon? If you want to run StreamController from source you can find the needed steps [here](https://streamcontroller.github.io/docs/latest/installation/#github)


> bash: syntax error near unexpected token `newline'

You have to run `git clone https://github.com/streamdeck-linux-gui/streamdeck-linux-gui.git` instead of `git clone <https://github.com/streamdeck-linux-gui/streamdeck-linux-gui.git>`

**Comment by FreeBSD-fan** [comment]
Ok, I was able to clone the repository on Mint and got a directory called: streamdeck-linux-gui
but there is no src directory under it.

**Comment by FreeBSD-fan** [comment]
I have tried two projects in the repository following instructions here: https://streamcontroller.github.io/docs/latest/installation/
and here: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui/blob/main/docs/installation/source.md

Both fail.  I see no reason to contribute more of my time.  I'm out.

**Comment by Core447** [comment]
Ok, sorry for the inconvenience. Let's keep this open in case someone else has a similar problem

**Comment by Core447** [comment]
@FreeBSD-fan 
You don't happen to have a Stream Deck XL, do you?

**Comment by FreeBSD-fan** [comment]
No, I have the original 15 key stream deck.

**Comment by Core447** [comment]
Could you maybe give it one last try? We have some new udev rules that you can add using this command: `sudo wget https://raw.githubusercontent.com/StreamController/StreamController/main/udev.rules -O /etc/udev/rules.d/60-streamdeck.rules`. You'll have to restart your computer after this command

**Comment by baecky** [comment]
I have a Stream Deck XL on Pop!_OS 22.04 LTS that did not get recognised and `sudo wget https://raw.githubusercontent.com/StreamController/StreamController/main/udev.rules -O /etc/udev/rules.d/60-streamdeck.rules` solved the issue for me.
Many thanks!

**Comment by kodiakcreativity** [comment]
I'm having the same problem, No Decks Discovered. using the latest from flathub. I've installed the udev rules and rebooted, streamdeck-UI and boatswain both detect and can work with the stream deck but streamcontroller cannot. the example_basic detects it and displayed a bunch of faces on the device. But StreamController still says no device detected. Any suggestions? This controller looks amazing...I just can't get it working! Mint 21.2

**Comment by Core447** [comment]
> streamdeck-UI and boatswain both detect and can work with the stream deck but streamcontroller cannot. the example_basic detects it and displayed a bunch of faces on the device

This doesn't seem to be a problem with the rules then. Which Stream Deck do you have? Can you make sure that all settings in Flatseal are set to the defaults? Could you maybe try the source version of StreamController ([instructions](https://streamcontroller.github.io/docs/latest/installation/#github)) if you feel comfortable doing that so?

**Comment by kodiakcreativity** [comment]
Thanks for the reply! its an XL deck. I have seen a couple of different versions of the udev file, but since the other applications were working I assumed that that wasn't going to be an issue.
my flatseal settings are not completely default, I have some environment settings changed as i was trying to apply themes to the flatpak apps. haven't gotten it to work yet, but that was going to be a question, is there anything I have to do with the permissions to allow the app to access the USB? although boatswain is also a flatpak install and it worked. oddly with that one got it to work by unplugging and reconnecting the streamdeck while the app was running and then it detected it. it hadn't before. not sure why. I'm a professional developer, so I could give compiling and running from source a shot and see what happens.
The example program did detect the deck and seemed able to control it.

**Comment by kodiakcreativity** [comment]
Not having the best luck, I worked through a couple of problems but I'm getting suck trying to run it, getting
raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Xdp not available

tried a couple of things to resolve that, no good so far though.

**Comment by Core447** [comment]
You might have to install these packages: `xdg-desktop-portal xdg-desktop-portal-gtk libportal libportal-gtk4 `

**Comment by kodiakcreativity** [comment]
Making progress! apt couldn't install libportal or libportal-gtk4, found a package libportal-gtk4-dev, maybe that covers it? that got be past the previous error. had to 
`pip install loguru `
next,
(just kind of doing a running log here of what I needed to do to get progress, in case it helps anyone else who wants to help with debugging or development of this amazing project)
then I get no module named 'usb'
`pip install pyusb`
no module named pyro5
`pip install pyro5`
then I get to

```
File "StreamController/src/windows/mainWindow/elements/DeckSettings/DeckSettingsPage.py", line 18, in <module>
    from GtkHelper.GtkHelper import BackButton
  File "Stream Deck/StreamController/GtkHelper/GtkHelper.py", line 376, in <module>
    class EntryRowWithoutTitle(Adw.EntryRow):
  File "/usr/lib/python3/dist-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Adw' object has no attribute 'EntryRow'
```

**Comment by Core447** [comment]
You probably have an old version of Adwaita (libadwaita). The current version is 1.5, and the EntryRow was added back in 1.2. I'm sorry that this takes so much of your time.

**Comment by Core447** [comment]
I'll try to reproduce this in a clean VM.

**Comment by kodiakcreativity** [comment]
I will have to see if I can update it. I've got a few dependencies out of date to build it myself, I wonder if there is a compiled version somewhere I could get. I have an update to mint 21.3 pending, I have just been putting it off. No idea if that would bring things up to date.

**Comment by kodiakcreativity** [comment]
I've got 1.1.7 currently, so that is likely the issue.

**Comment by phlepper** [comment]
Similar to kodiakcreativity, I followed the installation instructions and got the "Namespace Xdp not available".  I installed libportal-gtk4-dev (couldn't find libportal or libportal-gtk4).  Now I am getting:

```Traceback (most recent call last):
  File "/home/phlepper/Git-Projects/StreamController/main.py", line 35, in <module>
    from src.app import App
  File "/home/phlepper/Git-Projects/StreamController/src/app.py", line 32, in <module>
    from src.windows.mainWindow.mainWindow import MainWindow
  File "/home/phlepper/Git-Projects/StreamController/src/windows/mainWindow/mainWindow.py", line 28, in <module>
    from src.windows.mainWindow.elements.leftArea import LeftArea
  File "/home/phlepper/Git-Projects/StreamController/src/windows/mainWindow/elements/leftArea.py", line 26, in <module>
    from src.windows.mainWindow.elements.DeckStack import DeckStack
  File "/home/phlepper/Git-Projects/StreamController/src/windows/mainWindow/elements/DeckStack.py", line 30, in <module>
    from src.windows.mainWindow.elements.DeckStackChild import DeckStackChild
  File "/home/phlepper/Git-Projects/StreamController/src/windows/mainWindow/elements/DeckStackChild.py", line 24, in <module>
    from src.windows.mainWindow.elements.DeckSettings.DeckSettingsPage import DeckSettingsPage
  File "/home/phlepper/Git-Projects/StreamController/src/windows/mainWindow/elements/DeckSettings/DeckSettingsPage.py", line 18, in <module>
    from GtkHelper.GtkHelper import BackButton
  File "/home/phlepper/Git-Projects/StreamController/GtkHelper/GtkHelper.py", line 376, in <module>
    class EntryRowWithoutTitle(Adw.EntryRow):
  File "/home/phlepper/Git-Projects/StreamController/.venv/lib/python3.10/site-packages/gi/module.py", line 130, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Adw' object has no attribute 'EntryRow'
```

I'm running in Pop! OS 22.04.

Any help would be appreciated.  I tried running with the flatpak install, but it kept crashing (one of my pages was dependent on Google Chrome (window class google-chrome)).  When I removed that, it didn't crash, but I got lots of errors:

`xprop: error: Invalid window id format: 0x0.`

and then eventually

`src.backend.DeckManagement.DeckController:run:99 - Failed to set deck key image. Error: No HID device.`

and the Stream Deck buttons would be blank (I have the output file if you would find it helpful).

Thanks for your help getting this going.  I'm happy to provide additional information or try any troubleshooting you find helpful.

**Comment by Core447** [comment]
@phlepper Do you still have this problem on `1.5.0-beta.5` (released yesterday)?

**Comment by phlepper** [comment]
> @phlepper Do you still have this problem on `1.5.0-beta.5` (released yesterday)?

I still have *a* problem :)

```
python3 main.py
 _____ _                            _____             _             _ _           
/  ___| |                          /  __ \           | |           | | |          
\ `--.| |_ _ __ ___  __ _ _ __ ___ | /  \/ ___  _ __ | |_ _ __ ___ | | | ___ _ __ 
 `--. \ __| '__/ _ \/ _` | '_ ` _ \| |    / _ \| '_ \| __| '__/ _ \| | |/ _ \ '__|
/\__/ / |_| | |  __/ (_| | | | | | | \__/\ (_) | | | | |_| | | (_) | | |  __/ |   
\____/ \__|_|  \___|\__,_|_| |_| |_|\____/\___/|_| |_|\__|_|  \___/|_|_|\___|_|   

Traceback (most recent call last):
  File "/home/phlepper/Git-Projects/StreamController/main.py", line 44, in <module>
    from src.app import App
  File "/home/phlepper/Git-Projects/StreamController/src/app.py", line 25, in <module>
    from src.windows.Store.ResponsibleNotesDialog import ResponsibleNotesDialog
  File "/home/phlepper/Git-Projects/StreamController/src/windows/Store/ResponsibleNotesDialog.py", line 22, in <module>
    class ResponsibleNotesDialog(Adw.MessageDialog):
  File "/home/phlepper/Git-Projects/StreamController/.venv/lib/python3.10/site-packages/gi/module.py", line 130, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Adw' object has no attribute 'MessageDialog'
```

That was after deleting the GitHub folder, cloning, checking out the beta branch (`git checkout 1.5.0-beta.5` => `Note: switching to '1.5.0-beta.5'.`), and rerunning the pip requirements.  Not sure if I should do anything else?

Happy to provide more details, if needed.

**Comment by Core447** [comment]
> That was after deleting the GitHub folder, cloning, checking out the beta branch (`git checkout 1.5.0-beta.5` => `Note: switching to '1.5.0-beta.5'.`), and rerunning the pip requirements. Not sure if I should do anything else?

Seems like your system has a quite old version of libadwaita that is missing some widgets used by the app. I've mainly seen this on Ubuntu 22.04 and systems based on it and unfortunatly the only good way to get a newer version is to upgrate to Ubuntu 24.04 (or something based on it). However, you can just run the "normal" Flatpak and avoid all of this.

**Comment by Core447** [comment]
Closing this because of inactivity
