### ISSUE TITLE
BUG: Command doesn't execute when in lowest priority

### ISSUE THREAD

**Issue by v4u6h4n** [StreamController/StreamController#56]
**Describe the bug**
When the OS command action is in the last priority amongst other actions it doesn't execute, but it does if it is first. It seems like its the last position, if I run it as the second to last, or any other position, it executes fine.

```2024-04-20 13:07:32.000 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.001 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.001 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.001 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.001 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.001 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.042 | DEBUG    | src.backend.PageManagement.Page:load:65 - Loaded page ui_BL25K1B02780_135 in 0.04 seconds
2024-04-20 13:07:32.043 | INFO     | src.backend.DeckManagement.DeckController:load_page:524 - Loading page ui_BL25K1B02780_135 on deck BL25K1B02779
callback: <bound method PageSelector.update_selected of <PageSelector.PageSelector object at 0x7a091677be40 (src+windows+mainWindow+elements+PageSelector+PageSelector at 0x5a6af015fac0)>>
2024-04-20 13:07:32.045 | INFO     | src.backend.DeckManagement.DeckController:load_page:549 - Loaded page ui_BL25K1B02780_135 on deck BL25K1B02779
2024-04-20 13:07:32.087 | INFO     | src.backend.DeckManagement.DeckController:load_background:379 - Loading background in thread: 134178580465344
2024-04-20 13:07:32.125 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.125 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.126 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.126 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.126 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.126 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.131 | INFO     | src.backend.DeckManagement.DeckController:load_all_keys:463 - Loading all keys took 0.011733055114746094 seconds
2024-04-20 13:07:32.133 | DEBUG    | src.backend.DeckManagement.DeckController:update_all_keys:327 - Updating all keys took 0.0019180774688720703 seconds
2024-04-20 13:07:32.167 | DEBUG    | src.backend.PageManagement.Page:load:65 - Loaded page ui_BL25K1B02780_135 in 0.04 seconds
2024-04-20 13:07:32.171 | INFO     | src.backend.DeckManagement.DeckController:load_page:524 - Loading page ui_BL25K1B02780_135 on deck BL25K1B02763
callback: <bound method PageSelector.update_selected of <PageSelector.PageSelector object at 0x7a091677be40 (src+windows+mainWindow+elements+PageSelector+PageSelector at 0x5a6af015fac0)>>
2024-04-20 13:07:32.186 | INFO     | src.backend.DeckManagement.DeckController:load_page:549 - Loaded page ui_BL25K1B02780_135 on deck BL25K1B02763
2024-04-20 13:07:32.235 | INFO     | src.backend.DeckManagement.DeckController:load_background:379 - Loading background in thread: 134178146354880
2024-04-20 13:07:32.236 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.236 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.236 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.237 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.237 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.237 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.296 | INFO     | src.backend.DeckManagement.DeckController:load_all_keys:463 - Loading all keys took 0.008738994598388672 seconds
2024-04-20 13:07:32.298 | DEBUG    | src.backend.DeckManagement.DeckController:update_all_keys:327 - Updating all keys took 0.0019707679748535156 seconds
2024-04-20 13:07:32.307 | DEBUG    | src.backend.PageManagement.Page:load:65 - Loaded page ui_BL25K1B02780_135 in 0.07 seconds
2024-04-20 13:07:32.309 | INFO     | src.backend.DeckManagement.DeckController:load_page:524 - Loading page ui_BL25K1B02780_135 on deck BL25K1B02780
callback: <bound method PageSelector.update_selected of <PageSelector.PageSelector object at 0x7a091677be40 (src+windows+mainWindow+elements+PageSelector+PageSelector at 0x5a6af015fac0)>>
2024-04-20 13:07:32.312 | INFO     | src.backend.DeckManagement.DeckController:load_page:549 - Loaded page ui_BL25K1B02780_135 on deck BL25K1B02780
2024-04-20 13:07:32.362 | INFO     | src.backend.DeckManagement.DeckController:load_background:379 - Loading background in thread: 134178347681472
2024-04-20 13:07:32.362 | INFO     | src.windows.mainWindow.elements.PageSelector:on_change_page:128 - Load page: <src.backend.PageManagement.Page.Page object at 0x7a090c947d90>
2024-04-20 13:07:32.405 | INFO     | src.backend.DeckManagement.DeckController:load_page:524 - Loading page ui_BL25K1B02780_135 on deck BL25K1B02780
2024-04-20 13:07:32.416 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.416 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.416 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.416 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
callback: <bound method PageSelector.update_selected of <PageSelector.PageSelector object at 0x7a091677be40 (src+windows+mainWindow+elements+PageSelector+PageSelector at 0x5a6af015fac0)>>
2024-04-20 13:07:32.417 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.417 | INFO     | src.backend.PluginManager.ActionBase:__init__:67 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-04-20 13:07:32.418 | INFO     | src.backend.DeckManagement.DeckController:load_all_keys:463 - Loading all keys took 0.014006376266479492 seconds
2024-04-20 13:07:32.419 | INFO     | src.backend.DeckManagement.DeckController:load_page:549 - Loaded page ui_BL25K1B02780_135 on deck BL25K1B02780
2024-04-20 13:07:32.452 | DEBUG    | src.backend.DeckManagement.DeckController:update_all_keys:327 - Updating all keys took 0.034235239028930664 seconds
2024-04-20 13:07:32.471 | DEBUG    | src.backend.PageManagement.Page:load:65 - Loaded page ui_BL25K1B02780_135 in 0.06 seconds
2024-04-20 13:07:32.477 | INFO     | src.backend.DeckManagement.DeckController:load_page:524 - Loading page ui_BL25K1B02780_135 on deck BL19K1B01105
2024-04-20 13:07:32.484 | INFO     | src.backend.DeckManagement.DeckController:load_background:379 - Loading background in thread: 134177986971328
callback: <bound method PageSelector.update_selected of <PageSelector.PageSelector object at 0x7a091677be40 (src+windows+mainWindow+elements+PageSelector+PageSelector at 0x5a6af015fac0)>>
2024-04-20 13:07:32.530 | INFO     | src.backend.DeckManagement.DeckController:load_page:549 - Loaded page ui_BL25K1B02780_135 on deck BL19K1B01105
Exception in thread own_actions_key_down:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/v4u6h4n/StreamController/src/backend/DeckManagement/DeckController.py", line 1528, in own_actions_key_down
    action.on_key_down()
  File "/home/v4u6h4n/.var/app/com.core447.StreamController/data/plugins/com_core447_OSPlugin/actions/RunCommand/RunCommand.py", line 28, in on_key_down
    settings = self.get_settings()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/v4u6h4n/StreamController/src/backend/PluginManager/ActionBase.py", line 246, in get_settings
    return self.page.get_settings_for_action(self, coords = self.page_coords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_settings_for_action'
2024-04-20 13:07:32.578 | INFO     | src.backend.DeckManagement.DeckController:load_all_keys:463 - Loading all keys took 0.052480459213256836 seconds
2024-04-20 13:07:32.580 | INFO     | src.backend.DeckManagement.DeckController:load_background:379 - Loading background in thread: 134178347681472
2024-04-20 13:07:32.620 | DEBUG    | src.backend.DeckManagement.DeckController:update_all_keys:327 - Updating all keys took 0.04140925407409668 seconds
```

**Comment by Core447** [comment]
Do you have a "Change Page" action above the command?

**Comment by v4u6h4n** [comment]
Yeah, in this specific instance, it regards one of a handful of buttons which execute a page change action for all four of my stream decks, so I have 4x page change actions above the command action, like this:

```
<page action>
<page action>
<page action>
<page action>
<command action>
```

It seems to always work when the command action is first.

**Comment by Core447** [comment]
This should be fixed with the latest commits, can you please try again?

**Comment by v4u6h4n** [comment]
Okay looks like it's fixed.

**Comment by Core447** [comment]
Nice
