### ISSUE TITLE
BUG: Drag and drop images breaks

### ISSUE THREAD

**Issue by v4u6h4n** [StreamController/StreamController#65]
**Describe the bug**
Don't know the cause, perhaps dragging a file with the same name to the same button, or renaming or deleting the assigned image file. ~~Can be fixed by manually reassigning an image with the GUI.~~

```
Traceback (most recent call last):
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/KeyGrid.py", line 179, in on_button_drop
    self.handle_file_drop(drop, value, x, y)
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/KeyGrid.py", line 223, in handle_file_drop
    internal_path = gl.asset_manager_backend.add_custom_media_set_by_ui(url=url, path=path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/v4u6h4n/StreamController/src/backend/AssetManagerBackend.py", line 264, in add_custom_media_set_by_ui
    asset_id = gl.asset_manager_backend.add(asset_path=path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/v4u6h4n/StreamController/src/backend/AssetManagerBackend.py", line 66, in add
    internal_path = self.copy_asset(asset_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/v4u6h4n/StreamController/src/backend/AssetManagerBackend.py", line 155, in copy_asset
    shutil.copy(asset_path, dst_path)
  File "/usr/lib/python3.11/shutil.py", line 431, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.11/shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/home/v4u6h4n/.var/app/com.core447.StreamController/data/Assets/AssetManager/Assets/page_scene_single_black.svg'
Traceback (most recent call last):
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/KeyGrid.py", line 179, in on_button_drop
    self.handle_file_drop(drop, value, x, y)
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/KeyGrid.py", line 223, in handle_file_drop
    internal_path = gl.asset_manager_backend.add_custom_media_set_by_ui(url=url, path=path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/v4u6h4n/StreamController/src/backend/AssetManagerBackend.py", line 264, in add_custom_media_set_by_ui
    asset_id = gl.asset_manager_backend.add(asset_path=path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/v4u6h4n/StreamController/src/backend/AssetManagerBackend.py", line 66, in add
    internal_path = self.copy_asset(asset_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/v4u6h4n/StreamController/src/backend/AssetManagerBackend.py", line 155, in copy_asset
    shutil.copy(asset_path, dst_path)
  File "/usr/lib/python3.11/shutil.py", line 431, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.11/shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/home/v4u6h4n/.var/app/com.core447.StreamController/data/Assets/AssetManager/Assets/page_scene_quad_black.svg'
```

**UPDATE:** Had a look in the icons folder and it seems that the original image, with the same name, was not updated to the new image, with the same name. Manual deletion fixed the error for that specific button.

**Comment by Core447** [comment]
92f59cf06efddb4ddc295dc9acf4f0089616bf97 should fix most issues regarding assets with same names

**Comment by v4u6h4n** [comment]
Fixed, thanks!
