### ISSUE TITLE
BUG: Colour assignment fails when no actions or icon is assigned to button

### ISSUE THREAD

**Issue by v4u6h4n** [StreamController/StreamController#66]
Seems like colour assignment doesn't work when no image or action is already assigned to a button?

```
Traceback (most recent call last):
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/elements/BackgroundEditor.py", line 130, in on_change_color
    page.dict["keys"][f"{self.active_coords[0]}x{self.active_coords[1]}"].setdefault("background", {})
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '0x0'
Traceback (most recent call last):
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/elements/BackgroundEditor.py", line 130, in on_change_color
    page.dict["keys"][f"{self.active_coords[0]}x{self.active_coords[1]}"].setdefault("background", {})
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '1x0'
```

**Comment by Core447** [comment]
Fixed with 1cf9502895c8fb43caab492807cbe438fafe541c
