### ISSUE TITLE
BUG: Pages are created with no contents, won't load

### ISSUE THREAD

**Issue by v4u6h4n** [StreamController/StreamController#68]
Possibly related to the duplicate page function, as it was the only thing that I tested before this issue occured. All pages I create are created with no contents (only `{}`), I don't know if that's normal, but they are unusable. The only way to navigate to the page without errors (when navigating to the pages I cannot select any buttons without the side panel producing an error), is to copy paste the contents of another page and restart.

```
2024-04-21 15:37:02.795 | DEBUG    | src.backend.DeckManagement.DeckController:update_all_keys:327 - Updating all keys took 0.0007004737854003906 seconds
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/elements/BackgroundEditor.py", line 45, in load_for_coords
    self.label_group.load_for_coords(coords)
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/elements/BackgroundEditor.py", line 62, in load_for_coords
    self.expander.load_for_coords(coords)
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/elements/BackgroundEditor.py", line 81, in load_for_coords
    self.color_row.load_for_coords(coords)
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/elements/BackgroundEditor.py", line 142, in load_for_coords
    self.disconnect_signals()
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/elements/BackgroundEditor.py", line 112, in disconnect_signals
    self.color_chooser_button.disconnect_by_func(self.on_change_color)
TypeError: nothing connected to <bound method ColorRow.on_change_color of <BackgroundEditor.ColorRow object at 0x783bcc5ab140 (src+windows+mainWindow+elements+Sidebar+elements+BackgroundEditor+ColorRow at 0x63ea60942a60)>>
Traceback (most recent call last):
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/KeyGrid.py", line 354, in on_focus_in
    sidebar.load_for_coords((self.coords[1], self.coords[0]))
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/Sidebar.py", line 133, in load_for_coords
    self.key_editor.load_for_coords(coords)
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/Sidebar.py", line 192, in load_for_coords
    self.background_editor.load_for_coords(coords)
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/elements/BackgroundEditor.py", line 45, in load_for_coords
    self.label_group.load_for_coords(coords)
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/elements/BackgroundEditor.py", line 62, in load_for_coords
    self.expander.load_for_coords(coords)
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/elements/BackgroundEditor.py", line 81, in load_for_coords
    self.color_row.load_for_coords(coords)
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/elements/BackgroundEditor.py", line 142, in load_for_coords
    self.disconnect_signals()
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/elements/BackgroundEditor.py", line 112, in disconnect_signals
    self.color_chooser_button.disconnect_by_func(self.on_change_color)
TypeError: nothing connected to <bound method ColorRow.on_change_color of <BackgroundEditor.ColorRow object at 0x783bcc5ab140 (src+windows+mainWindow+elements+Sidebar+elements+BackgroundEditor+ColorRow at 0x63ea60942a60)>>
Traceback (most recent call last):
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/KeyGrid.py", line 354, in on_focus_in
    sidebar.load_for_coords((self.coords[1], self.coords[0]))
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/Sidebar.py", line 133, in load_for_coords
    self.key_editor.load_for_coords(coords)
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/Sidebar.py", line 192, in load_for_coords
    self.background_editor.load_for_coords(coords)
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/elements/BackgroundEditor.py", line 45, in load_for_coords
    self.label_group.load_for_coords(coords)
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/elements/BackgroundEditor.py", line 62, in load_for_coords
    self.expander.load_for_coords(coords)
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/elements/BackgroundEditor.py", line 81, in load_for_coords
    self.color_row.load_for_coords(coords)
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/elements/BackgroundEditor.py", line 142, in load_for_coords
    self.disconnect_signals()
  File "/home/v4u6h4n/StreamController/src/windows/mainWindow/elements/Sidebar/elements/BackgroundEditor.py", line 112, in disconnect_signals
    self.color_chooser_button.disconnect_by_func(self.on_change_color)
TypeError: nothing connected to <bound method ColorRow.on_change_color of <BackgroundEditor.ColorRow object at 0x783bcc5ab140 (src+windows+mainWindow+elements+Sidebar+elements+BackgroundEditor+ColorRow at 0x63ea60942a60)>>
```

**Comment by Core447** [comment]
This should be fixed now

**Comment by v4u6h4n** [comment]
Yeah looks like its fixed now
